package com.fonality.util;

import java.util.Map;

public class FCSCountry {

	private String iso2;
	private String iso3;
	private String name;
	private String netsuiteName;
	
	public static Map<String, FCSCountry> countryMap;
	
	public FCSCountry(String iso2, String iso3, String name, String netsuiteName) {
		this.iso2 = iso2;
		this.iso3 = iso3;
		this.name = name;
		this.netsuiteName = netsuiteName;
		countryMap.put(iso2, this);
		countryMap.put(iso3, this);
		countryMap.put(name, this);
		countryMap.put(netsuiteName, this);
	}
	
	public String getIso2() {
		return iso2;
	}
	public String getIso3() {
		return iso3;
	}
	public String getName() {
		return name;
	}
	public String getNetsuiteName() {
		return netsuiteName;
	}


	public static FCSCountry BOUVETISLAND = new FCSCountry("BV", "BVT", "Bouvet Island", "_bouvetIsland");
	public static FCSCountry BERMUDA = new FCSCountry("BM", "BMU", "Bermuda", "_bermuda");
	public static FCSCountry NIGER = new FCSCountry("NE", "NER", "Niger", "_niger");
	public static FCSCountry NIGERIA = new FCSCountry("NG", "NGA", "Nigeria", "_nigeria");
	public static FCSCountry PALAU = new FCSCountry("PW", "PLW", "Palau", "_palau");
	public static FCSCountry NEWZEALAND = new FCSCountry("NZ", "NZL", "New Zealand", "_newZealand");
	public static FCSCountry BOZNIAHERZEGOVINA = new FCSCountry("BA", "BIH", "Bosnia and Herzegovina", "_bosniaAndHerzegovina");
	public static FCSCountry MONACO = new FCSCountry("MC", "MCO", "Monaco", "_monaco");
	public static FCSCountry TUVALU = new FCSCountry("TV", "TUV", "Tuvalu", "_tuvalu");
	public static FCSCountry PARAGUAY = new FCSCountry("PY", "PRY", "Paraguay", "_paraguay");
	public static FCSCountry FIJI = new FCSCountry("FJ", "FJI", "Fiji", "_fiji");
	public static FCSCountry GREENLAND = new FCSCountry("GL", "GRL", "Greenland", "_greenland");
	public static FCSCountry MALAWI = new FCSCountry("MW", "MWI", "Malawi", "_malawi");
	public static FCSCountry GREECE = new FCSCountry("GR", "GRC", "Greece", "_greece");
	public static FCSCountry NAMIBIA = new FCSCountry("NA", "NAM", "Namibia", "_namibia");
	public static FCSCountry QATAR = new FCSCountry("QA", "QAT", "Qatar", "_qatar");
	public static FCSCountry GERMANY = new FCSCountry("DE", "DEU", "Germany", "_germany");
	public static FCSCountry MONGOLIA = new FCSCountry("MN", "MNG", "Mongolia", "_mongolia");
	public static FCSCountry ALBANIA = new FCSCountry("AL", "ALB", "Albania", "_albania");
	public static FCSCountry TOGO = new FCSCountry("TG", "TGO", "Togo", "_togo");
	public static FCSCountry SWITZERLAND = new FCSCountry("CH", "CHE", "Switzerland", "_switzerland");
	public static FCSCountry AUSTRIA = new FCSCountry("AT", "AUT", "Austria", "_austria");
	public static FCSCountry SURINAME = new FCSCountry("SR", "SUR", "Suriname", "_suriname");
	public static FCSCountry CANADA = new FCSCountry("CA", "CAN", "Canada", "_canada");
	public static FCSCountry CAPEVERDE = new FCSCountry("CV", "CPV", "Cape Verde", "_capVerde");
	public static FCSCountry GAMBIA = new FCSCountry("GM", "GMB", "Gambia", "_gambia");
	public static FCSCountry BULGARIA = new FCSCountry("BG", "BGR", "Bulgaria", "_bulgaria");
	public static FCSCountry THAILAND = new FCSCountry("TH", "THA", "Thailand", "_thailand");
	public static FCSCountry COLOMBIA = new FCSCountry("CO", "COL", "Colombia", "_colombia");
	public static FCSCountry COSTARICA = new FCSCountry("CR", "CRI", "Costa Rica", "_costaRica");
	public static FCSCountry MALTA = new FCSCountry("MT", "MLT", "Malta", "_malta");
	public static FCSCountry SLOVAKIA = new FCSCountry("SK", "SVK", "Slovakia", "_slovakRepublic");
	public static FCSCountry LUXEMBOURG = new FCSCountry("LU", "LUX", "Luxembourg", "_luxembourg");
	public static FCSCountry SIERRALEONE = new FCSCountry("SL", "SLE", "Sierra Leone", "_sierraLeone");
	public static FCSCountry MALAYSIA = new FCSCountry("MY", "MYS", "Malaysia", "_malaysia");
	public static FCSCountry CHAD = new FCSCountry("TD", "TCD", "Chad", "_chad");
	public static FCSCountry WESTERNSAHARA = new FCSCountry("EH", "ESH", "Western Sahara", "_westernSahara");
	public static FCSCountry PUERTORICO = new FCSCountry("PR", "PRI", "Puerto Rico", "_puertoRico");
	public static FCSCountry ITALY = new FCSCountry("IT", "ITA", "Italy", "_italy");
	public static FCSCountry LITHUANIA = new FCSCountry("LT", "LTU", "Lithuania", "_lithuania");
	public static FCSCountry SINGAPORE = new FCSCountry("SG", "SGP", "Singapore", "_singapore");
	public static FCSCountry TURKEY = new FCSCountry("TR", "TUR", "Turkey", "_turkey");
	public static FCSCountry FRANCE = new FCSCountry("FR", "FRA", "France", "_france");
	public static FCSCountry MADAGASCAR = new FCSCountry("MG", "MDG", "Madagascar", "_madagascar");
	public static FCSCountry OMAN = new FCSCountry("OM", "OMN", "Oman", "_oman");
	public static FCSCountry BHUTAN = new FCSCountry("BT", "BTN", "Bhutan", "_bhutan");
	public static FCSCountry ESTONIA = new FCSCountry("EE", "EST", "Estonia", "_estonia");
	public static FCSCountry ANGUILLA = new FCSCountry("AI", "AIA", "Anguilla", "_anguilla");
	public static FCSCountry KENYA = new FCSCountry("KE", "KEN", "Kenya", "_kenya");
	public static FCSCountry ANTIGUABARBUDA = new FCSCountry("AG", "ATG", "Antigua and Barbuda", "_antiguaAndBarbuda");
	public static FCSCountry BARBADOS = new FCSCountry("BB", "BRB", "Barbados", "_barbados");
	public static FCSCountry EASTTIMOR = new FCSCountry("TP", "TMP", "East Timor", "_eastTimor");
	public static FCSCountry GEORGIA = new FCSCountry("GE", "GEO", "Georgia", "_georgia");
	public static FCSCountry TAJIKISTAN = new FCSCountry("TJ", "TJK", "Tajikistan", "_tajikistan");
	public static FCSCountry BENIN = new FCSCountry("BJ", "BEN", "Benin", "_benin");
	public static FCSCountry MAURITANIA = new FCSCountry("MR", "MRT", "Mauritania", "_mauritania");
	public static FCSCountry CYPRUS = new FCSCountry("CY", "CYP", "Cyprus", "_cyprus");
	public static FCSCountry MARSHALLISLANDS = new FCSCountry("MH", "MHL", "Marshall Islands", "_marshallIslands");
	public static FCSCountry PAKISTAN = new FCSCountry("PK", "PAK", "Pakistan", "_pakistan");
	public static FCSCountry EIRTREA = new FCSCountry("ER", "ERI", "Eritrea", "_eritrea");
	public static FCSCountry PAPUANEWGUINEA = new FCSCountry("PG", "PNG", "Papua New Guinea", "_papuaNewGuinea");
	public static FCSCountry LATVIA = new FCSCountry("LV", "LVA", "Latvia", "_latvia");
	public static FCSCountry BOLIVIA = new FCSCountry("BO", "BOL", "Bolivia", "_bolivia");
	public static FCSCountry SVALBARDANDJANDJANMAYENISLANDS = new FCSCountry("SJ", "SJM", "Svalbard and Jan Mayen Islands", "_svalbardAndJanMayenIslands");
	public static FCSCountry TOKELAU = new FCSCountry("TK", "TKL", "Tokelau", "_tokelau");
	public static FCSCountry ECUADOR = new FCSCountry("EC", "ECU", "Ecuador", "_ecuador");
	public static FCSCountry BURUNDI = new FCSCountry("BI", "BDI", "Burundi", "_burundi");
	public static FCSCountry ANDORRA = new FCSCountry("AD", "AND", "Andora", "_andorra");
	public static FCSCountry NICARAGUA = new FCSCountry("NI", "NIC", "Nicaragua", "_nicaragua");
	public static FCSCountry DOMINICA = new FCSCountry("DM", "DMA", "Dominica", "_dominica");
	public static FCSCountry MONTSERRAT = new FCSCountry("MS", "MSR", "Montserrat", "_montserrat");
	public static FCSCountry KAZAKHSTAN = new FCSCountry("KZ", "KAZ", "Kazakhstan", "_kazakhstan");
	public static FCSCountry CHILE = new FCSCountry("CL", "CHL", "Chile", "_chile");
	public static FCSCountry MYANMAR = new FCSCountry("MM", "MMR", "Myanmar", "_myanmar");
	public static FCSCountry CAYMANISLANDS = new FCSCountry("KY", "CYM", "Cayman Islands", "_caymanIslands");
	public static FCSCountry VANUATU = new FCSCountry("VU", "VUT", "Vanuatu", "_vanuatu");
	public static FCSCountry GABON = new FCSCountry("GA", "GAB", "Gabon", "_gabon");
	public static FCSCountry UNITEDKINGDOM = new FCSCountry("BG", "GBR", "United Kingdom", "_unitedKingdomGB");
	public static FCSCountry BAHAMAS = new FCSCountry("BS", "BHS", "Bahamas", "_bahamas");
	public static FCSCountry VIETNAM = new FCSCountry("VN", "VNM", "Vietnam", "_vietnam");
	public static FCSCountry YEMEN = new FCSCountry("YE", "YEM", "Yemen", "_yemen");
	public static FCSCountry AUSTRALIA = new FCSCountry("AU", "AUS", "Australia", "_australia");
	public static FCSCountry ALGERIA = new FCSCountry("DZ", "DZA", "Algeria", "_algeria");
	public static FCSCountry MARTINIQUE = new FCSCountry("MQ", "MTQ", "Martinique", "_martinique");
	public static FCSCountry YUGOSLAVIA = new FCSCountry("YU", "YUG", "Yugoslavia", "_yugoslavia");
	public static FCSCountry PERU = new FCSCountry("PE", "PER", "Peru", "_peru");
	public static FCSCountry NEPAL = new FCSCountry("NP", "NPL", "Nepal", "_nepal");
	public static FCSCountry GHANA = new FCSCountry("GH", "GHA", "Ghana", "_ghana");
	public static FCSCountry AZERBAIJAN = new FCSCountry("AZ", "AZE", "Azerbaijan", "_azerbaijan");
	public static FCSCountry GIBRALATAR = new FCSCountry("GI", "GIB", "Gibraltar", "_gibraltar");
	public static FCSCountry GRENADA = new FCSCountry("GD", "GRD", "Grenada", "_grenada");
	public static FCSCountry NIUE = new FCSCountry("NU", "NIU", "Niue", "_niue");
	public static FCSCountry SLOVENIA = new FCSCountry("SI", "SVN", "Slovenia", "_slovenia");
	public static FCSCountry MACAU = new FCSCountry("MO", "MAC", "Macau", "_macau");
	public static FCSCountry ARGENTINA = new FCSCountry("AR", "ARG", "Arentina", "_argentina");
	public static FCSCountry SAINTLUCIA = new FCSCountry("LC", "LCA", "Saint Lucia", "_saintLucia");
	public static FCSCountry IRELAND = new FCSCountry("IE", "IRL", "Ireland", "_ireland");
	public static FCSCountry EQUATORIALGUNIEA = new FCSCountry("GQ", "GNQ", "Equatorial Guinea", "_equatorialGuinea");
	public static FCSCountry VENEZUELA = new FCSCountry("VE", "VEN", "Venezuela", "_venezuela");
	public static FCSCountry SOMALIA = new FCSCountry("SO", "SOM", "Somalia", "_somalia");
	public static FCSCountry ISRAEL = new FCSCountry("IL", "ISR", "Israel", "_israel");
	public static FCSCountry HAITI = new FCSCountry("HT", "HTI", "Haiti", "_haiti");
	public static FCSCountry LEBANON = new FCSCountry("LB", "LBN", "Lebanon", "_lebanon");
	public static FCSCountry SOUTHAFRICA = new FCSCountry("ZA", "ZAF", "South Africa", "_southAfrica");
	public static FCSCountry UZBEKISTAN = new FCSCountry("UZ", "UZB", "Uzbekistan", "_uzbekistan");
	public static FCSCountry NORFOLKISLAND = new FCSCountry("NF", "NFK", "Norfolk Island", "_norfolkIsland");
	public static FCSCountry NAURU = new FCSCountry("NR", "NRU", "Nauru", "_nauru");
	public static FCSCountry AMERICANSAMOA = new FCSCountry("AS", "ASM", "American Samoa", "_americanSamoa");
	public static FCSCountry SAINTKITTSNEVIS = new FCSCountry("KN", "KNA", "Saint Kitts and Nevis", "_saintKittsAndNevis");
	public static FCSCountry LESOTHO = new FCSCountry("LS", "LSO", "Lesotho", "_lesotho");
	public static FCSCountry NORTHERNMARIANAISLANDS = new FCSCountry("MP", "MNP", "Northern Mariana Islands", "_northernMarianaIslands");
	public static FCSCountry SAUDIARABIA = new FCSCountry("SA", "SAU", "Saudi Arabia", "_saudiArabia");
	public static FCSCountry GUINEA = new FCSCountry("GN", "GIN", "Guinea", "_guinea");
	public static FCSCountry NEWCALEDONIA = new FCSCountry("NC", "NCL", "New Caledonia", "_newCaledonia");
	public static FCSCountry COMOROS = new FCSCountry("KM", "COM", "Comoros", "_comoros");
	public static FCSCountry RWANDA = new FCSCountry("RW", "RWA", "Rwanda", "_rwanda");
	public static FCSCountry BELGIUM = new FCSCountry("BE", "BEL", "Belgium", "_belgium");
	public static FCSCountry CAEROON = new FCSCountry("CM", "CMR", "Cameroon", "_cameroon");
	public static FCSCountry ARMENIA = new FCSCountry("AM", "ARM", "Armenia", "_armenia");
	public static FCSCountry HONDURAS = new FCSCountry("HN", "HND", "Honduras", "_honduras");
	public static FCSCountry JORDAN = new FCSCountry("JO", "JOR", "Jordan", "_jordan");
	public static FCSCountry TUNISIA = new FCSCountry("TN", "TUN", "Tunisia", "_tunisia");
	public static FCSCountry TONGA = new FCSCountry("TO", "TON", "Tonga", "_tonga");
	public static FCSCountry MALI = new FCSCountry("ML", "MLI", "Mali", "_mali");
	public static FCSCountry ELSALVADOR = new FCSCountry("SV", "SLV", "El Salvador", "_elSalvador");
	public static FCSCountry POLAND = new FCSCountry("PL", "POL", "Poland", "_poland");
	public static FCSCountry LIECHTENSTEIN = new FCSCountry("LI", "LIE", "Liechtenstein", "_liechtenstein");
	public static FCSCountry MAURITIUS = new FCSCountry("MU", "MUS", "Mauritius", "_mauritius");
	public static FCSCountry CAMBODIA = new FCSCountry("KH", "KHM", "Cambodia", "_combodia");
	public static FCSCountry IRAQ = new FCSCountry("IQ", "IRQ", "Iraq", "_iraq");
	public static FCSCountry CONGO = new FCSCountry("CG", "COG", "Congo", "_congoRepublicOf");
	public static FCSCountry SEYCHELLES = new FCSCountry("SC", "SYC", "Seychelles", "_seychelles");
	public static FCSCountry SANMARINAO = new FCSCountry("SM", "SMR", "San Marino", "_sanMarino");
	public static FCSCountry BELARUS = new FCSCountry("BY", "BLR", "Belarus", "_belarus");
	public static FCSCountry FINLAND = new FCSCountry("FI", "FIN", "Finland", "_finland");
	public static FCSCountry BRAZIL = new FCSCountry("BR", "BRA", "Brazil", "_brazil");
	public static FCSCountry CROATIA = new FCSCountry("HR", "HRV", "Croatia", "_croatiaHrvatska");
	public static FCSCountry ICELAND = new FCSCountry("IS", "ISL", "Iceland", "_iceland");
	public static FCSCountry FRENCHPOLYNESIA = new FCSCountry("PF", "PYF", "French Polynesia", "_frenchPolynesia");
	public static FCSCountry SWEDEN = new FCSCountry("SE", "SWE", "Sweden", "_sweden");
	public static FCSCountry DOMINICANREPUBLIC = new FCSCountry("DO", "DOM", "Dominican Republic", "_dominicanRepublic");
	public static FCSCountry PANAMA = new FCSCountry("PA", "PAN", "Panama", "_panama");
	public static FCSCountry BELIZE = new FCSCountry("BZ", "BLZ", "Belize", "_belize");
	public static FCSCountry CUBA = new FCSCountry("CU", "CUB", "Cuba", "_cuba");
	public static FCSCountry GUADELOUPE = new FCSCountry("GP", "GLP", "Guadeloupe", "_guadeloupe");
	public static FCSCountry HUNGARY = new FCSCountry("HU", "HUN", "Hungary", "_hungary");
	public static FCSCountry MEXICO = new FCSCountry("MX", "MEX", "Mexico", "_mexico");
	public static FCSCountry FRENCHGUIANA = new FCSCountry("GF", "GUF", "French Guiana", "_frenchGuiana");
	public static FCSCountry DENMARK = new FCSCountry("DK", "DNK", "Denmark", "_denmark");
	public static FCSCountry KUWAIT = new FCSCountry("KW", "KWT", "Kuwait", "_kuwait");
	public static FCSCountry ZAMBIA = new FCSCountry("ZM", "ZMB", "Zambia", "_zambia");
	public static FCSCountry PORTUGAL = new FCSCountry("PT", "PRT", "Portugal", "_portugal");
	public static FCSCountry INDIA = new FCSCountry("IN", "IND", "India", "_india");
	public static FCSCountry DJIBOUTI = new FCSCountry("DJ", "DJI", "Djibouti", "_djibouti");
	public static FCSCountry JAPAN = new FCSCountry("JP", "JPN", "Japan", "_japan");
	public static FCSCountry UGANDA = new FCSCountry("UG", "UGA", "Uganda", "_uganda");
	public static FCSCountry URUGUAY = new FCSCountry("UY", "URY", "Uruguay", "_uruguay");
	public static FCSCountry BOTSWANA = new FCSCountry("BW", "BWA", "Botswana", "_botswana");
	public static FCSCountry GUYANA = new FCSCountry("GY", "GUY", "Guyana", "_guyana");
	public static FCSCountry CHINA = new FCSCountry("CN", "CHN", "China", "_china");
	public static FCSCountry TURKSCAICOS = new FCSCountry("TC", "TCA", "Turks and Caicos Islands", "_turksAndCaicosIslands");
	public static FCSCountry SAOTOMEPRINCIPE = new FCSCountry("ST", "STP", "Sao Tome and Principe", "_saoTomeAndPrincipe");
	public static FCSCountry PHILIPPINES = new FCSCountry("PH", "PHL", "Philippines", "_philippines");
	public static FCSCountry BAHRAIN = new FCSCountry("BH", "BHR", "Bahrain", "_bahrain");
	public static FCSCountry ARUBA = new FCSCountry("AW", "ABW", "Aruba", "_aruba");
	public static FCSCountry NORWAY = new FCSCountry("NO", "NOR", "Norway", "_norway");
	public static FCSCountry NETHERLANDS = new FCSCountry("NL", "NLD", "Netherlands", "_netherlands");
	public static FCSCountry MOROCCO = new FCSCountry("MA", "MAR", "Morocco", "_morocco");
	public static FCSCountry SPAIN = new FCSCountry("ES", "ESP", "Spain", "_spain");
	public static FCSCountry MOZAMBIQUE = new FCSCountry("MZ", "MOZ", "Mozambique", "_mozambique");
	public static FCSCountry SAINTVINCENTGRENADINES = new FCSCountry("VC", "VCT", "Saint Vincent and the Grenadines", "_saintVincentAndTheGrenadines");
	public static FCSCountry TRINIDADTOBAGO = new FCSCountry("TT", "TTO", "Trinidad and Tobago", "_trinidadAndTobago");
	public static FCSCountry CENTRALAFRICANREPUBLIC = new FCSCountry("CF", "CAF", "Central African Republic", "_centralAfricanRepublic");
	public static FCSCountry ROMANIA = new FCSCountry("RO", "ROM", "Romania", "_romania");
	public static FCSCountry BANGLADESH = new FCSCountry("BD", "BGD", "Bangladesh", "_bangladesh");
	public static FCSCountry SUDAN = new FCSCountry("SD", "SDN", "Sudan", "_sudan");
	public static FCSCountry COOKISLANDS = new FCSCountry("CK", "COK", "Cook Islands", "_cookIslands");
	public static FCSCountry GUAM = new FCSCountry("GU", "GUM", "Guam", "_guam");
	public static FCSCountry MALDIVES = new FCSCountry("MV", "MDV", "Maldives", "_maldives");
	public static FCSCountry ANGOLA = new FCSCountry("AO", "AGO", "Angola", "_angola");
	public static FCSCountry SRILANKA = new FCSCountry("LK", "LKA", "Sri Lanka", "_sriLanka");
	public static FCSCountry JAMAICA = new FCSCountry("JM", "JAM", "Jamaica", "_jamaica");
	public static FCSCountry UKRAINE = new FCSCountry("UA", "UKR", "Ukraine", "_ukraine");
	public static FCSCountry ZIMBABWE = new FCSCountry("ZW", "ZWE", "Zimbabwe", "_zimbabwe");
	public static FCSCountry BURKINAFASO = new FCSCountry("BF", "BFA", "Burkina Faso", "_burkinaFaso");
	public static FCSCountry KIRIBATI = new FCSCountry("KI", "KIR", "Kiribati", "_kiribati");
	public static FCSCountry USA = new FCSCountry("US", "USA", "United States of America", "_unitedStates");
	public static FCSCountry EGYPT = new FCSCountry("EG", "EGY", "Egypt", "_egypt");
	public static FCSCountry SENEGAL = new FCSCountry("SN", "SEN", "Senegal", "_senegal");
	public static FCSCountry LIBERIA = new FCSCountry("LR", "LBR", "Liberia", "_liberia");
	public static FCSCountry TURKMENISTAN = new FCSCountry("TM", "TKM", "Turkmenistan", "_turkmenistan");
	public static FCSCountry SWAZILAND = new FCSCountry("SZ", "SWZ", "Swaziland", "_swaziland");
	public static FCSCountry SOLOMONISLANDS = new FCSCountry("SB", "SLB", "Solomon Islands", "_solomonIslands");
	public static FCSCountry GUATEMALA = new FCSCountry("GT", "GTM", "Guatemala", "_guatemala");
	public static FCSCountry CZECHREPUBLIC = new FCSCountry("CZ", "CZE", "Czech Republic", "_czechRepublic");
	public static FCSCountry INDONESIA = new FCSCountry("ID", "IDN", "Indonesia", "_indonesia");
	public static FCSCountry KYRGYZSTAN = new FCSCountry("KG", "KGZ", "Kyrgyzstan", "_kyrgyzstan");
	public static FCSCountry UNITEDARABEMIRATES = new FCSCountry("AE", "ARE", "United Arab Emirates", "_unitedArabEmirates");
	public static FCSCountry AFGHANISTAN = new FCSCountry("AF", "AFG", "Afghanistan", "_afghanistan");
	public static FCSCountry BRUNEI = new FCSCountry("BN", "BRN", "Brunei Darussalam", "_bruneiDarussalam");
	public static FCSCountry WALLISFUTUNAISLANDS = new FCSCountry("WF", "WLF", "Wallis and Futuna Islands", "_wallisAndFutunaIslands");
}
