
package com.fonality.billsoft;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EZTaxWebService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://eztaxasp.billsoft.com/EZTaxWebService/EZTaxWebService.svc?singleWsdl")
public class EZTaxWebService
    extends Service
{

    private final static URL EZTAXWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException EZTAXWEBSERVICE_EXCEPTION;
    private final static QName EZTAXWEBSERVICE_QNAME = new QName("http://tempuri.org/", "EZTaxWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://eztaxasp.billsoft.com/EZTaxWebService/EZTaxWebService.svc?singleWsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EZTAXWEBSERVICE_WSDL_LOCATION = url;
        EZTAXWEBSERVICE_EXCEPTION = e;
    }

    public EZTaxWebService() {
        super(__getWsdlLocation(), EZTAXWEBSERVICE_QNAME);
    }

    public EZTaxWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EZTAXWEBSERVICE_QNAME, features);
    }

    public EZTaxWebService(URL wsdlLocation) {
        super(wsdlLocation, EZTAXWEBSERVICE_QNAME);
    }

    public EZTaxWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EZTAXWEBSERVICE_QNAME, features);
    }

    public EZTaxWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EZTaxWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IEZTaxWebService
     */
    @WebEndpoint(name = "BasicHttpBinding_IEZTaxWebService")
    public IEZTaxWebService getBasicHttpBindingIEZTaxWebService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IEZTaxWebService"), IEZTaxWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEZTaxWebService
     */
    @WebEndpoint(name = "BasicHttpBinding_IEZTaxWebService")
    public IEZTaxWebService getBasicHttpBindingIEZTaxWebService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IEZTaxWebService"), IEZTaxWebService.class, features);
    }

    /**
     * 
     * @return
     *     returns IEZTaxWebService
     */
    @WebEndpoint(name = "BasicHttpBinding_IEZTaxWebService1")
    public IEZTaxWebService getBasicHttpBindingIEZTaxWebService1() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IEZTaxWebService1"), IEZTaxWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEZTaxWebService
     */
    @WebEndpoint(name = "BasicHttpBinding_IEZTaxWebService1")
    public IEZTaxWebService getBasicHttpBindingIEZTaxWebService1(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IEZTaxWebService1"), IEZTaxWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EZTAXWEBSERVICE_EXCEPTION!= null) {
            throw EZTAXWEBSERVICE_EXCEPTION;
        }
        return EZTAXWEBSERVICE_WSDL_LOCATION;
    }

}
