
package com.fonality.billsoft;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IEZTaxWebService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IEZTaxWebService {


    /**
     * 
     * @param aTransaction
     * @return
     *     returns com.fonality.bs.ArrayOfTaxData
     */
    @WebMethod(operationName = "CalcTaxesWithZipAddress", action = "http://tempuri.org/IEZTaxWebService/CalcTaxesWithZipAddress")
    @WebResult(name = "CalcTaxesWithZipAddressResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcTaxesWithZipAddress", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcTaxesWithZipAddress")
    @ResponseWrapper(localName = "CalcTaxesWithZipAddressResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcTaxesWithZipAddressResponse")
    public ArrayOfTaxData calcTaxesWithZipAddress(
        @WebParam(name = "aTransaction", targetNamespace = "http://tempuri.org/")
        Transaction aTransaction);

    /**
     * 
     * @param aTransaction
     * @return
     *     returns com.fonality.bs.ArrayOfTaxData
     */
    @WebMethod(operationName = "CalcTaxesWithFipsCode", action = "http://tempuri.org/IEZTaxWebService/CalcTaxesWithFipsCode")
    @WebResult(name = "CalcTaxesWithFipsCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcTaxesWithFipsCode", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcTaxesWithFipsCode")
    @ResponseWrapper(localName = "CalcTaxesWithFipsCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcTaxesWithFipsCodeResponse")
    public ArrayOfTaxData calcTaxesWithFipsCode(
        @WebParam(name = "aTransaction", targetNamespace = "http://tempuri.org/")
        Transaction aTransaction);

    /**
     * 
     * @param aTransaction
     * @return
     *     returns com.fonality.bs.ArrayOfTaxData
     */
    @WebMethod(operationName = "CalcTaxesWithPCode", action = "http://tempuri.org/IEZTaxWebService/CalcTaxesWithPCode")
    @WebResult(name = "CalcTaxesWithPCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcTaxesWithPCode", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcTaxesWithPCode")
    @ResponseWrapper(localName = "CalcTaxesWithPCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcTaxesWithPCodeResponse")
    public ArrayOfTaxData calcTaxesWithPCode(
        @WebParam(name = "aTransaction", targetNamespace = "http://tempuri.org/")
        Transaction aTransaction);

    /**
     * 
     * @param aTransaction
     * @return
     *     returns com.fonality.bs.ArrayOfTaxData
     */
    @WebMethod(operationName = "CalcTaxesWithNpaNxx", action = "http://tempuri.org/IEZTaxWebService/CalcTaxesWithNpaNxx")
    @WebResult(name = "CalcTaxesWithNpaNxxResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcTaxesWithNpaNxx", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcTaxesWithNpaNxx")
    @ResponseWrapper(localName = "CalcTaxesWithNpaNxxResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcTaxesWithNpaNxxResponse")
    public ArrayOfTaxData calcTaxesWithNpaNxx(
        @WebParam(name = "aTransaction", targetNamespace = "http://tempuri.org/")
        Transaction aTransaction);

    /**
     * 
     * @param anAdjustment
     * @return
     *     returns com.fonality.bs.ArrayOfTaxData
     */
    @WebMethod(operationName = "CalcAdjWithZipAddress", action = "http://tempuri.org/IEZTaxWebService/CalcAdjWithZipAddress")
    @WebResult(name = "CalcAdjWithZipAddressResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcAdjWithZipAddress", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcAdjWithZipAddress")
    @ResponseWrapper(localName = "CalcAdjWithZipAddressResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcAdjWithZipAddressResponse")
    public ArrayOfTaxData calcAdjWithZipAddress(
        @WebParam(name = "anAdjustment", targetNamespace = "http://tempuri.org/")
        Transaction anAdjustment);

    /**
     * 
     * @param anAdjustment
     * @return
     *     returns com.fonality.bs.ArrayOfTaxData
     */
    @WebMethod(operationName = "CalcAdjWithFipsCode", action = "http://tempuri.org/IEZTaxWebService/CalcAdjWithFipsCode")
    @WebResult(name = "CalcAdjWithFipsCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcAdjWithFipsCode", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcAdjWithFipsCode")
    @ResponseWrapper(localName = "CalcAdjWithFipsCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcAdjWithFipsCodeResponse")
    public ArrayOfTaxData calcAdjWithFipsCode(
        @WebParam(name = "anAdjustment", targetNamespace = "http://tempuri.org/")
        Transaction anAdjustment);

    /**
     * 
     * @param anAdjustment
     * @return
     *     returns com.fonality.bs.ArrayOfTaxData
     */
    @WebMethod(operationName = "CalcAdjWithPCode", action = "http://tempuri.org/IEZTaxWebService/CalcAdjWithPCode")
    @WebResult(name = "CalcAdjWithPCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcAdjWithPCode", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcAdjWithPCode")
    @ResponseWrapper(localName = "CalcAdjWithPCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcAdjWithPCodeResponse")
    public ArrayOfTaxData calcAdjWithPCode(
        @WebParam(name = "anAdjustment", targetNamespace = "http://tempuri.org/")
        Transaction anAdjustment);

    /**
     * 
     * @param anAdjustment
     * @return
     *     returns com.fonality.bs.ArrayOfTaxData
     */
    @WebMethod(operationName = "CalcAdjWithNpaNxx", action = "http://tempuri.org/IEZTaxWebService/CalcAdjWithNpaNxx")
    @WebResult(name = "CalcAdjWithNpaNxxResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcAdjWithNpaNxx", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcAdjWithNpaNxx")
    @ResponseWrapper(localName = "CalcAdjWithNpaNxxResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcAdjWithNpaNxxResponse")
    public ArrayOfTaxData calcAdjWithNpaNxx(
        @WebParam(name = "anAdjustment", targetNamespace = "http://tempuri.org/")
        Transaction anAdjustment);

    /**
     * 
     * @param aTransaction
     * @return
     *     returns com.fonality.bs.ReverseTaxResults
     */
    @WebMethod(operationName = "CalcReverseTaxesWithPCode", action = "http://tempuri.org/IEZTaxWebService/CalcReverseTaxesWithPCode")
    @WebResult(name = "CalcReverseTaxesWithPCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcReverseTaxesWithPCode", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcReverseTaxesWithPCode")
    @ResponseWrapper(localName = "CalcReverseTaxesWithPCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcReverseTaxesWithPCodeResponse")
    public ReverseTaxResults calcReverseTaxesWithPCode(
        @WebParam(name = "aTransaction", targetNamespace = "http://tempuri.org/")
        Transaction aTransaction);

    /**
     * 
     * @param aTransaction
     * @return
     *     returns com.fonality.bs.ReverseTaxResults
     */
    @WebMethod(operationName = "CalcReverseTaxesWithNpaNxx", action = "http://tempuri.org/IEZTaxWebService/CalcReverseTaxesWithNpaNxx")
    @WebResult(name = "CalcReverseTaxesWithNpaNxxResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcReverseTaxesWithNpaNxx", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcReverseTaxesWithNpaNxx")
    @ResponseWrapper(localName = "CalcReverseTaxesWithNpaNxxResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcReverseTaxesWithNpaNxxResponse")
    public ReverseTaxResults calcReverseTaxesWithNpaNxx(
        @WebParam(name = "aTransaction", targetNamespace = "http://tempuri.org/")
        Transaction aTransaction);

    /**
     * 
     * @param aTransaction
     * @return
     *     returns com.fonality.bs.ReverseTaxResults
     */
    @WebMethod(operationName = "CalcReverseTaxesWithFipsCode", action = "http://tempuri.org/IEZTaxWebService/CalcReverseTaxesWithFipsCode")
    @WebResult(name = "CalcReverseTaxesWithFipsCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcReverseTaxesWithFipsCode", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcReverseTaxesWithFipsCode")
    @ResponseWrapper(localName = "CalcReverseTaxesWithFipsCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcReverseTaxesWithFipsCodeResponse")
    public ReverseTaxResults calcReverseTaxesWithFipsCode(
        @WebParam(name = "aTransaction", targetNamespace = "http://tempuri.org/")
        Transaction aTransaction);

    /**
     * 
     * @param aTransaction
     * @return
     *     returns com.fonality.bs.ReverseTaxResults
     */
    @WebMethod(operationName = "CalcReverseTaxesWithZipAddress", action = "http://tempuri.org/IEZTaxWebService/CalcReverseTaxesWithZipAddress")
    @WebResult(name = "CalcReverseTaxesWithZipAddressResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcReverseTaxesWithZipAddress", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcReverseTaxesWithZipAddress")
    @ResponseWrapper(localName = "CalcReverseTaxesWithZipAddressResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcReverseTaxesWithZipAddressResponse")
    public ReverseTaxResults calcReverseTaxesWithZipAddress(
        @WebParam(name = "aTransaction", targetNamespace = "http://tempuri.org/")
        Transaction aTransaction);

    /**
     * 
     * @param anAdjustment
     * @return
     *     returns com.fonality.bs.ReverseTaxResults
     */
    @WebMethod(operationName = "CalcReverseAdjWithPCode", action = "http://tempuri.org/IEZTaxWebService/CalcReverseAdjWithPCode")
    @WebResult(name = "CalcReverseAdjWithPCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcReverseAdjWithPCode", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcReverseAdjWithPCode")
    @ResponseWrapper(localName = "CalcReverseAdjWithPCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcReverseAdjWithPCodeResponse")
    public ReverseTaxResults calcReverseAdjWithPCode(
        @WebParam(name = "anAdjustment", targetNamespace = "http://tempuri.org/")
        Transaction anAdjustment);

    /**
     * 
     * @param anAdjustment
     * @return
     *     returns com.fonality.bs.ReverseTaxResults
     */
    @WebMethod(operationName = "CalcReverseAdjWithNpaNxx", action = "http://tempuri.org/IEZTaxWebService/CalcReverseAdjWithNpaNxx")
    @WebResult(name = "CalcReverseAdjWithNpaNxxResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcReverseAdjWithNpaNxx", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcReverseAdjWithNpaNxx")
    @ResponseWrapper(localName = "CalcReverseAdjWithNpaNxxResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcReverseAdjWithNpaNxxResponse")
    public ReverseTaxResults calcReverseAdjWithNpaNxx(
        @WebParam(name = "anAdjustment", targetNamespace = "http://tempuri.org/")
        Transaction anAdjustment);

    /**
     * 
     * @param anAdjustment
     * @return
     *     returns com.fonality.bs.ReverseTaxResults
     */
    @WebMethod(operationName = "CalcReverseAdjWithFipsCode", action = "http://tempuri.org/IEZTaxWebService/CalcReverseAdjWithFipsCode")
    @WebResult(name = "CalcReverseAdjWithFipsCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcReverseAdjWithFipsCode", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcReverseAdjWithFipsCode")
    @ResponseWrapper(localName = "CalcReverseAdjWithFipsCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcReverseAdjWithFipsCodeResponse")
    public ReverseTaxResults calcReverseAdjWithFipsCode(
        @WebParam(name = "anAdjustment", targetNamespace = "http://tempuri.org/")
        Transaction anAdjustment);

    /**
     * 
     * @param anAdjustment
     * @return
     *     returns com.fonality.bs.ReverseTaxResults
     */
    @WebMethod(operationName = "CalcReverseAdjWithZipAddress", action = "http://tempuri.org/IEZTaxWebService/CalcReverseAdjWithZipAddress")
    @WebResult(name = "CalcReverseAdjWithZipAddressResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcReverseAdjWithZipAddress", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcReverseAdjWithZipAddress")
    @ResponseWrapper(localName = "CalcReverseAdjWithZipAddressResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.CalcReverseAdjWithZipAddressResponse")
    public ReverseTaxResults calcReverseAdjWithZipAddress(
        @WebParam(name = "anAdjustment", targetNamespace = "http://tempuri.org/")
        Transaction anAdjustment);

    /**
     * 
     * @param anExclusionList
     * @param aTransaction
     * @param aNexusList
     * @return
     *     returns com.fonality.bs.ArrayOfTaxData
     */
    @WebMethod(operationName = "SAUCalcTaxesWithPCode", action = "http://tempuri.org/IEZTaxWebService/SAUCalcTaxesWithPCode")
    @WebResult(name = "SAUCalcTaxesWithPCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SAUCalcTaxesWithPCode", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcTaxesWithPCode")
    @ResponseWrapper(localName = "SAUCalcTaxesWithPCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcTaxesWithPCodeResponse")
    public ArrayOfTaxData sauCalcTaxesWithPCode(
        @WebParam(name = "aTransaction", targetNamespace = "http://tempuri.org/")
        SalesUseTransaction aTransaction,
        @WebParam(name = "aNexusList", targetNamespace = "http://tempuri.org/")
        ArrayOfNexus aNexusList,
        @WebParam(name = "anExclusionList", targetNamespace = "http://tempuri.org/")
        ArrayOfExclusion anExclusionList);

    /**
     * 
     * @param anExclusionList
     * @param aTransaction
     * @param aNexusList
     * @return
     *     returns com.fonality.bs.ArrayOfTaxData
     */
    @WebMethod(operationName = "SAUCalcTaxesWithFipsCode", action = "http://tempuri.org/IEZTaxWebService/SAUCalcTaxesWithFipsCode")
    @WebResult(name = "SAUCalcTaxesWithFipsCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SAUCalcTaxesWithFipsCode", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcTaxesWithFipsCode")
    @ResponseWrapper(localName = "SAUCalcTaxesWithFipsCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcTaxesWithFipsCodeResponse")
    public ArrayOfTaxData sauCalcTaxesWithFipsCode(
        @WebParam(name = "aTransaction", targetNamespace = "http://tempuri.org/")
        SalesUseTransaction aTransaction,
        @WebParam(name = "aNexusList", targetNamespace = "http://tempuri.org/")
        ArrayOfNexus aNexusList,
        @WebParam(name = "anExclusionList", targetNamespace = "http://tempuri.org/")
        ArrayOfExclusion anExclusionList);

    /**
     * 
     * @param anExclusionList
     * @param aTransaction
     * @param aNexusList
     * @return
     *     returns com.fonality.bs.ArrayOfTaxData
     */
    @WebMethod(operationName = "SAUCalcTaxesWithZipAddress", action = "http://tempuri.org/IEZTaxWebService/SAUCalcTaxesWithZipAddress")
    @WebResult(name = "SAUCalcTaxesWithZipAddressResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SAUCalcTaxesWithZipAddress", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcTaxesWithZipAddress")
    @ResponseWrapper(localName = "SAUCalcTaxesWithZipAddressResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcTaxesWithZipAddressResponse")
    public ArrayOfTaxData sauCalcTaxesWithZipAddress(
        @WebParam(name = "aTransaction", targetNamespace = "http://tempuri.org/")
        SalesUseTransaction aTransaction,
        @WebParam(name = "aNexusList", targetNamespace = "http://tempuri.org/")
        ArrayOfNexus aNexusList,
        @WebParam(name = "anExclusionList", targetNamespace = "http://tempuri.org/")
        ArrayOfExclusion anExclusionList);

    /**
     * 
     * @param anExclusionList
     * @param aNexusList
     * @param anAdjustment
     * @return
     *     returns com.fonality.bs.ArrayOfTaxData
     */
    @WebMethod(operationName = "SAUCalcAdjWithPCode", action = "http://tempuri.org/IEZTaxWebService/SAUCalcAdjWithPCode")
    @WebResult(name = "SAUCalcAdjWithPCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SAUCalcAdjWithPCode", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcAdjWithPCode")
    @ResponseWrapper(localName = "SAUCalcAdjWithPCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcAdjWithPCodeResponse")
    public ArrayOfTaxData sauCalcAdjWithPCode(
        @WebParam(name = "anAdjustment", targetNamespace = "http://tempuri.org/")
        SalesUseTransaction anAdjustment,
        @WebParam(name = "aNexusList", targetNamespace = "http://tempuri.org/")
        ArrayOfNexus aNexusList,
        @WebParam(name = "anExclusionList", targetNamespace = "http://tempuri.org/")
        ArrayOfExclusion anExclusionList);

    /**
     * 
     * @param anExclusionList
     * @param aNexusList
     * @param anAdjustment
     * @return
     *     returns com.fonality.bs.ArrayOfTaxData
     */
    @WebMethod(operationName = "SAUCalcAdjWithFipsCode", action = "http://tempuri.org/IEZTaxWebService/SAUCalcAdjWithFipsCode")
    @WebResult(name = "SAUCalcAdjWithFipsCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SAUCalcAdjWithFipsCode", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcAdjWithFipsCode")
    @ResponseWrapper(localName = "SAUCalcAdjWithFipsCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcAdjWithFipsCodeResponse")
    public ArrayOfTaxData sauCalcAdjWithFipsCode(
        @WebParam(name = "anAdjustment", targetNamespace = "http://tempuri.org/")
        SalesUseTransaction anAdjustment,
        @WebParam(name = "aNexusList", targetNamespace = "http://tempuri.org/")
        ArrayOfNexus aNexusList,
        @WebParam(name = "anExclusionList", targetNamespace = "http://tempuri.org/")
        ArrayOfExclusion anExclusionList);

    /**
     * 
     * @param anExclusionList
     * @param aNexusList
     * @param anAdjustment
     * @return
     *     returns com.fonality.bs.ArrayOfTaxData
     */
    @WebMethod(operationName = "SAUCalcAdjWithZipAddress", action = "http://tempuri.org/IEZTaxWebService/SAUCalcAdjWithZipAddress")
    @WebResult(name = "SAUCalcAdjWithZipAddressResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SAUCalcAdjWithZipAddress", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcAdjWithZipAddress")
    @ResponseWrapper(localName = "SAUCalcAdjWithZipAddressResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcAdjWithZipAddressResponse")
    public ArrayOfTaxData sauCalcAdjWithZipAddress(
        @WebParam(name = "anAdjustment", targetNamespace = "http://tempuri.org/")
        SalesUseTransaction anAdjustment,
        @WebParam(name = "aNexusList", targetNamespace = "http://tempuri.org/")
        ArrayOfNexus aNexusList,
        @WebParam(name = "anExclusionList", targetNamespace = "http://tempuri.org/")
        ArrayOfExclusion anExclusionList);

    /**
     * 
     * @param anExclusionList
     * @param aTransaction
     * @param aNexusList
     * @return
     *     returns com.fonality.bs.ReverseTaxResults
     */
    @WebMethod(operationName = "SAUCalcReverseTaxesWithPCode", action = "http://tempuri.org/IEZTaxWebService/SAUCalcReverseTaxesWithPCode")
    @WebResult(name = "SAUCalcReverseTaxesWithPCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SAUCalcReverseTaxesWithPCode", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcReverseTaxesWithPCode")
    @ResponseWrapper(localName = "SAUCalcReverseTaxesWithPCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcReverseTaxesWithPCodeResponse")
    public ReverseTaxResults sauCalcReverseTaxesWithPCode(
        @WebParam(name = "aTransaction", targetNamespace = "http://tempuri.org/")
        SalesUseTransaction aTransaction,
        @WebParam(name = "aNexusList", targetNamespace = "http://tempuri.org/")
        ArrayOfNexus aNexusList,
        @WebParam(name = "anExclusionList", targetNamespace = "http://tempuri.org/")
        ArrayOfExclusion anExclusionList);

    /**
     * 
     * @param anExclusionList
     * @param aTransaction
     * @param aNexusList
     * @return
     *     returns com.fonality.bs.ReverseTaxResults
     */
    @WebMethod(operationName = "SAUCalcReverseTaxesWithFipsCode", action = "http://tempuri.org/IEZTaxWebService/SAUCalcReverseTaxesWithFipsCode")
    @WebResult(name = "SAUCalcReverseTaxesWithFipsCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SAUCalcReverseTaxesWithFipsCode", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcReverseTaxesWithFipsCode")
    @ResponseWrapper(localName = "SAUCalcReverseTaxesWithFipsCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcReverseTaxesWithFipsCodeResponse")
    public ReverseTaxResults sauCalcReverseTaxesWithFipsCode(
        @WebParam(name = "aTransaction", targetNamespace = "http://tempuri.org/")
        SalesUseTransaction aTransaction,
        @WebParam(name = "aNexusList", targetNamespace = "http://tempuri.org/")
        ArrayOfNexus aNexusList,
        @WebParam(name = "anExclusionList", targetNamespace = "http://tempuri.org/")
        ArrayOfExclusion anExclusionList);

    /**
     * 
     * @param anExclusionList
     * @param aTransaction
     * @param aNexusList
     * @return
     *     returns com.fonality.bs.ReverseTaxResults
     */
    @WebMethod(operationName = "SAUCalcReverseTaxesWithZipAddress", action = "http://tempuri.org/IEZTaxWebService/SAUCalcReverseTaxesWithZipAddress")
    @WebResult(name = "SAUCalcReverseTaxesWithZipAddressResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SAUCalcReverseTaxesWithZipAddress", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcReverseTaxesWithZipAddress")
    @ResponseWrapper(localName = "SAUCalcReverseTaxesWithZipAddressResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcReverseTaxesWithZipAddressResponse")
    public ReverseTaxResults sauCalcReverseTaxesWithZipAddress(
        @WebParam(name = "aTransaction", targetNamespace = "http://tempuri.org/")
        SalesUseTransaction aTransaction,
        @WebParam(name = "aNexusList", targetNamespace = "http://tempuri.org/")
        ArrayOfNexus aNexusList,
        @WebParam(name = "anExclusionList", targetNamespace = "http://tempuri.org/")
        ArrayOfExclusion anExclusionList);

    /**
     * 
     * @param anExclusionList
     * @param aNexusList
     * @param anAdjustment
     * @return
     *     returns com.fonality.bs.ReverseTaxResults
     */
    @WebMethod(operationName = "SAUCalcReverseAdjWithPCode", action = "http://tempuri.org/IEZTaxWebService/SAUCalcReverseAdjWithPCode")
    @WebResult(name = "SAUCalcReverseAdjWithPCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SAUCalcReverseAdjWithPCode", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcReverseAdjWithPCode")
    @ResponseWrapper(localName = "SAUCalcReverseAdjWithPCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcReverseAdjWithPCodeResponse")
    public ReverseTaxResults sauCalcReverseAdjWithPCode(
        @WebParam(name = "anAdjustment", targetNamespace = "http://tempuri.org/")
        SalesUseTransaction anAdjustment,
        @WebParam(name = "aNexusList", targetNamespace = "http://tempuri.org/")
        ArrayOfNexus aNexusList,
        @WebParam(name = "anExclusionList", targetNamespace = "http://tempuri.org/")
        ArrayOfExclusion anExclusionList);

    /**
     * 
     * @param anExclusionList
     * @param aNexusList
     * @param anAdjustment
     * @return
     *     returns com.fonality.bs.ReverseTaxResults
     */
    @WebMethod(operationName = "SAUCalcReverseAdjWithFipsCode", action = "http://tempuri.org/IEZTaxWebService/SAUCalcReverseAdjWithFipsCode")
    @WebResult(name = "SAUCalcReverseAdjWithFipsCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SAUCalcReverseAdjWithFipsCode", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcReverseAdjWithFipsCode")
    @ResponseWrapper(localName = "SAUCalcReverseAdjWithFipsCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcReverseAdjWithFipsCodeResponse")
    public ReverseTaxResults sauCalcReverseAdjWithFipsCode(
        @WebParam(name = "anAdjustment", targetNamespace = "http://tempuri.org/")
        SalesUseTransaction anAdjustment,
        @WebParam(name = "aNexusList", targetNamespace = "http://tempuri.org/")
        ArrayOfNexus aNexusList,
        @WebParam(name = "anExclusionList", targetNamespace = "http://tempuri.org/")
        ArrayOfExclusion anExclusionList);

    /**
     * 
     * @param anExclusionList
     * @param aNexusList
     * @param anAdjustment
     * @return
     *     returns com.fonality.bs.ReverseTaxResults
     */
    @WebMethod(operationName = "SAUCalcReverseAdjWithZipAddress", action = "http://tempuri.org/IEZTaxWebService/SAUCalcReverseAdjWithZipAddress")
    @WebResult(name = "SAUCalcReverseAdjWithZipAddressResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SAUCalcReverseAdjWithZipAddress", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcReverseAdjWithZipAddress")
    @ResponseWrapper(localName = "SAUCalcReverseAdjWithZipAddressResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcReverseAdjWithZipAddressResponse")
    public ReverseTaxResults sauCalcReverseAdjWithZipAddress(
        @WebParam(name = "anAdjustment", targetNamespace = "http://tempuri.org/")
        SalesUseTransaction anAdjustment,
        @WebParam(name = "aNexusList", targetNamespace = "http://tempuri.org/")
        ArrayOfNexus aNexusList,
        @WebParam(name = "anExclusionList", targetNamespace = "http://tempuri.org/")
        ArrayOfExclusion anExclusionList);

    /**
     * 
     * @param anExclusionList
     * @param aTransactionList
     * @param anAdjustmentList
     * @param aNexusList
     * @return
     *     returns com.fonality.bs.ArrayOfCustomerTaxData
     */
    @WebMethod(operationName = "SAUCalcTaxesAndAdjWithPCodeInCustMode", action = "http://tempuri.org/IEZTaxWebService/SAUCalcTaxesAndAdjWithPCodeInCustMode")
    @WebResult(name = "SAUCalcTaxesAndAdjWithPCodeInCustModeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SAUCalcTaxesAndAdjWithPCodeInCustMode", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcTaxesAndAdjWithPCodeInCustMode")
    @ResponseWrapper(localName = "SAUCalcTaxesAndAdjWithPCodeInCustModeResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcTaxesAndAdjWithPCodeInCustModeResponse")
    public ArrayOfCustomerTaxData sauCalcTaxesAndAdjWithPCodeInCustMode(
        @WebParam(name = "aTransactionList", targetNamespace = "http://tempuri.org/")
        ArrayOfSalesUseTransaction aTransactionList,
        @WebParam(name = "anAdjustmentList", targetNamespace = "http://tempuri.org/")
        ArrayOfSalesUseTransaction anAdjustmentList,
        @WebParam(name = "aNexusList", targetNamespace = "http://tempuri.org/")
        ArrayOfNexus aNexusList,
        @WebParam(name = "anExclusionList", targetNamespace = "http://tempuri.org/")
        ArrayOfExclusion anExclusionList);

    /**
     * 
     * @param anExclusionList
     * @param aTransactionList
     * @param anAdjustmentList
     * @param aNexusList
     * @return
     *     returns com.fonality.bs.ArrayOfCustomerTaxData
     */
    @WebMethod(operationName = "SAUCalcTaxesAndAdjWithFipsCodeInCustMode", action = "http://tempuri.org/IEZTaxWebService/SAUCalcTaxesAndAdjWithFipsCodeInCustMode")
    @WebResult(name = "SAUCalcTaxesAndAdjWithFipsCodeInCustModeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SAUCalcTaxesAndAdjWithFipsCodeInCustMode", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcTaxesAndAdjWithFipsCodeInCustMode")
    @ResponseWrapper(localName = "SAUCalcTaxesAndAdjWithFipsCodeInCustModeResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcTaxesAndAdjWithFipsCodeInCustModeResponse")
    public ArrayOfCustomerTaxData sauCalcTaxesAndAdjWithFipsCodeInCustMode(
        @WebParam(name = "aTransactionList", targetNamespace = "http://tempuri.org/")
        ArrayOfSalesUseTransaction aTransactionList,
        @WebParam(name = "anAdjustmentList", targetNamespace = "http://tempuri.org/")
        ArrayOfSalesUseTransaction anAdjustmentList,
        @WebParam(name = "aNexusList", targetNamespace = "http://tempuri.org/")
        ArrayOfNexus aNexusList,
        @WebParam(name = "anExclusionList", targetNamespace = "http://tempuri.org/")
        ArrayOfExclusion anExclusionList);

    /**
     * 
     * @param anExclusionList
     * @param aTransactionList
     * @param anAdjustmentList
     * @param aNexusList
     * @return
     *     returns com.fonality.bs.ArrayOfCustomerTaxData
     */
    @WebMethod(operationName = "SAUCalcTaxesAndAdjWithZipAddressInCustMode", action = "http://tempuri.org/IEZTaxWebService/SAUCalcTaxesAndAdjWithZipAddressInCustMode")
    @WebResult(name = "SAUCalcTaxesAndAdjWithZipAddressInCustModeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SAUCalcTaxesAndAdjWithZipAddressInCustMode", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcTaxesAndAdjWithZipAddressInCustMode")
    @ResponseWrapper(localName = "SAUCalcTaxesAndAdjWithZipAddressInCustModeResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.SAUCalcTaxesAndAdjWithZipAddressInCustModeResponse")
    public ArrayOfCustomerTaxData sauCalcTaxesAndAdjWithZipAddressInCustMode(
        @WebParam(name = "aTransactionList", targetNamespace = "http://tempuri.org/")
        ArrayOfSalesUseTransaction aTransactionList,
        @WebParam(name = "anAdjustmentList", targetNamespace = "http://tempuri.org/")
        ArrayOfSalesUseTransaction anAdjustmentList,
        @WebParam(name = "aNexusList", targetNamespace = "http://tempuri.org/")
        ArrayOfNexus aNexusList,
        @WebParam(name = "anExclusionList", targetNamespace = "http://tempuri.org/")
        ArrayOfExclusion anExclusionList);

    /**
     * 
     * @param aPCode
     * @return
     *     returns com.fonality.bs.ArrayOfAddressData
     */
    @WebMethod(operationName = "GetAddress", action = "http://tempuri.org/IEZTaxWebService/GetAddress")
    @WebResult(name = "GetAddressResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAddress", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.GetAddress")
    @ResponseWrapper(localName = "GetAddressResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.GetAddressResponse")
    public ArrayOfAddressData getAddress(
        @WebParam(name = "aPCode", targetNamespace = "http://tempuri.org/")
        Long aPCode);

    /**
     * 
     * @param aPCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PCodeToFips", action = "http://tempuri.org/IEZTaxWebService/PCodeToFips")
    @WebResult(name = "PCodeToFipsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PCodeToFips", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.PCodeToFips")
    @ResponseWrapper(localName = "PCodeToFipsResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.PCodeToFipsResponse")
    public String pCodeToFips(
        @WebParam(name = "aPCode", targetNamespace = "http://tempuri.org/")
        Long aPCode);

    /**
     * 
     * @param aFips
     * @return
     *     returns java.lang.Long
     */
    @WebMethod(operationName = "FipsToPCode", action = "http://tempuri.org/IEZTaxWebService/FipsToPCode")
    @WebResult(name = "FipsToPCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "FipsToPCode", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.FipsToPCode")
    @ResponseWrapper(localName = "FipsToPCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.FipsToPCodeResponse")
    public Long fipsToPCode(
        @WebParam(name = "aFips", targetNamespace = "http://tempuri.org/")
        String aFips);

    /**
     * 
     * @param anNpaNxx
     * @return
     *     returns java.lang.Long
     */
    @WebMethod(operationName = "NpaNxxToPCode", action = "http://tempuri.org/IEZTaxWebService/NpaNxxToPCode")
    @WebResult(name = "NpaNxxToPCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "NpaNxxToPCode", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.NpaNxxToPCode")
    @ResponseWrapper(localName = "NpaNxxToPCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.NpaNxxToPCodeResponse")
    public Long npaNxxToPCode(
        @WebParam(name = "anNpaNxx", targetNamespace = "http://tempuri.org/")
        Long anNpaNxx);

    /**
     * 
     * @param aZipAddress
     * @return
     *     returns java.lang.Long
     */
    @WebMethod(operationName = "ZipToPCode", action = "http://tempuri.org/IEZTaxWebService/ZipToPCode")
    @WebResult(name = "ZipToPCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ZipToPCode", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.ZipToPCode")
    @ResponseWrapper(localName = "ZipToPCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.ZipToPCodeResponse")
    public Long zipToPCode(
        @WebParam(name = "aZipAddress", targetNamespace = "http://tempuri.org/")
        ZipAddress aZipAddress);

    /**
     * 
     * @param aTaxType
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetTaxCategory", action = "http://tempuri.org/IEZTaxWebService/GetTaxCategory")
    @WebResult(name = "GetTaxCategoryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTaxCategory", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.GetTaxCategory")
    @ResponseWrapper(localName = "GetTaxCategoryResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.GetTaxCategoryResponse")
    public String getTaxCategory(
        @WebParam(name = "aTaxType", targetNamespace = "http://tempuri.org/")
        Integer aTaxType);

    /**
     * 
     * @param aTaxType
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetTaxDescription", action = "http://tempuri.org/IEZTaxWebService/GetTaxDescription")
    @WebResult(name = "GetTaxDescriptionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTaxDescription", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.GetTaxDescription")
    @ResponseWrapper(localName = "GetTaxDescriptionResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.GetTaxDescriptionResponse")
    public String getTaxDescription(
        @WebParam(name = "aTaxType", targetNamespace = "http://tempuri.org/")
        Integer aTaxType);

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "GetServerTime", action = "http://tempuri.org/IEZTaxWebService/GetServerTime")
    @WebResult(name = "GetServerTimeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetServerTime", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.GetServerTime")
    @ResponseWrapper(localName = "GetServerTimeResponse", targetNamespace = "http://tempuri.org/", className = "com.fonality.bs.GetServerTimeResponse")
    public XMLGregorianCalendar getServerTime();

}
