package Fap::Model::Fcs::Ref::Feature;
use strict;


sub options {
return {
	ivr_message_scheduler=>1,
	music_on_hold=>2,
	ring_all_blast_group_=>3,
	custom_upload_voice_prompts=>4,
	voicemail_to_email=>5,
	call_return_from_voicemail=>6,
	call_forwarding=>7,
	foncall=>8,
	extension_groups=>9,
	voicemail_groups=>10,
	reporting_exporting_to_csv=>11,
	call_quality_reports=>12,
	toll_restrictions=>13,
	ivr_authentication=>14,
	selectable_outbound_cid_number=>15,
	server_linking=>16,
	unlimited_conference_rooms=>17,
	agent_login_logout=>18,
	unlimited_call_queues=>19,
	acd_reporting=>20,
	user_csv_import=>21,
	call_recording=>22,
	hot_desk=>23,
	call_monitor_barge_whisper=>24,
	hud_web_launcher=>25,
	basic_salesforce_connector=>26,
	basic_sugarcrm_connector=>27,
	find_me_follow_me=>28,
	call_out_from_voicemail=>29,
	voicemail_sms_pager_notification=>30,
	voicemail_transcription=>31,
	screen_sharing=>32,
	hud_mobile=>33,
	record_all=>34,
	phones_self_provisioning=>35,
	branding=>36,
	billing=>37,
	emergency_e911=>38,
	virtual_extensions=>39,
	voip_ready=>40,
	uae=>41,
	hud_web_softphone=>42,
	unlimited_basic_license=>43,
	unlimited_voicemail_extension=>44,
	unlimited_virtual_extension=>45,
	custom_voicemail_greeting=>46,
	hud_basic_call_status=>47,
	hud_individual_chat=>48,
	hud_group_chat=>49,
	hud_visual_voicemail=>50,
	hud_visual_call_parking=>51,
	hud_conference=>52,
	hud_drag_and_drop_transfer_steal=>53,
	hud_desktop_alerts=>54,
	hud_google_contact_integration=>55,
	simple_queue=>56,
	hud_file_sharing=>57,
	hud_on_the_fly_recording=>58,
	hud_advanced_call_status=>59,
	hud_real_time_queue_status=>60,
	hud_queue_broadcast=>61,
	hud_barge_monitor_whisper=>62,
	acd_schedule_call_recording=>63,
	acd_edit_logout_reason_codes=>64,
	acd_view_edit_queues=>65,
	unlimited_fcs_user_license=>66,
	unlimited_fcs_pro_user_license=>67,
	unlimited_fcs_call_center_user_license=>68,
};
}


1;
