package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * BundlePriceModel generated by hbm2java
 */
@Entity
@Table(name = "bundle_price_model", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = {
		"bundle_id", "price_model_id" }))
public class BundlePriceModel implements java.io.Serializable {

	private Integer bundlePriceModelId;
	private TaxMapping taxMapping;
	private PriceModel priceModel;
	private Bundle bundle;
	private Date created;
	private Date updated;

	public BundlePriceModel() {
	}

	public BundlePriceModel(TaxMapping taxMapping, PriceModel priceModel,
			Bundle bundle, Date created, Date updated) {
		this.taxMapping = taxMapping;
		this.priceModel = priceModel;
		this.bundle = bundle;
		this.created = created;
		this.updated = updated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "bundle_price_model_id", unique = true, nullable = false)
	public Integer getBundlePriceModelId() {
		return this.bundlePriceModelId;
	}

	public void setBundlePriceModelId(Integer bundlePriceModelId) {
		this.bundlePriceModelId = bundlePriceModelId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tax_mapping_id", nullable = false)
	public TaxMapping getTaxMapping() {
		return this.taxMapping;
	}

	public void setTaxMapping(TaxMapping taxMapping) {
		this.taxMapping = taxMapping;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "price_model_id", nullable = false)
	public PriceModel getPriceModel() {
		return this.priceModel;
	}

	public void setPriceModel(PriceModel priceModel) {
		this.priceModel = priceModel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bundle_id", nullable = false)
	public Bundle getBundle() {
		return this.bundle;
	}

	public void setBundle(Bundle bundle) {
		this.bundle = bundle;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 0)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

}
