package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * BundleCategory generated by hbm2java
 */
@Entity
@Table(name = "bundle_category", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class BundleCategory implements java.io.Serializable {

	private Integer bundleCategoryId;
	private DiscountCategory discountCategory;
	private String name;
	private Date created;
	private Date updated;
	private Set<Bundle> bundles = new HashSet<Bundle>(0);

	public BundleCategory() {
	}

	public BundleCategory(DiscountCategory discountCategory, String name,
			Date created, Date updated) {
		this.discountCategory = discountCategory;
		this.name = name;
		this.created = created;
		this.updated = updated;
	}

	public BundleCategory(DiscountCategory discountCategory, String name,
			Date created, Date updated, Set<Bundle> bundles) {
		this.discountCategory = discountCategory;
		this.name = name;
		this.created = created;
		this.updated = updated;
		this.bundles = bundles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "bundle_category_id", unique = true, nullable = false)
	public Integer getBundleCategoryId() {
		return this.bundleCategoryId;
	}

	public void setBundleCategoryId(Integer bundleCategoryId) {
		this.bundleCategoryId = bundleCategoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "discount_category_id", nullable = false)
	public DiscountCategory getDiscountCategory() {
		return this.discountCategory;
	}

	public void setDiscountCategory(DiscountCategory discountCategory) {
		this.discountCategory = discountCategory;
	}

	@Column(name = "name", unique = true, nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 0)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bundleCategory")
	public Set<Bundle> getBundles() {
		return this.bundles;
	}

	public void setBundles(Set<Bundle> bundles) {
		this.bundles = bundles;
	}

}
