package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * BundleDiscount generated by hbm2java
 */
@Entity
@Table(name = "bundle_discount", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = {
		"bundle_id", "discount_id" }))
public class BundleDiscount implements java.io.Serializable {

	private Integer bundleDiscountId;
	private Discount discount;
	private Bundle bundle;
	private Date created;

	public BundleDiscount() {
	}

	public BundleDiscount(Discount discount, Bundle bundle, Date created) {
		this.discount = discount;
		this.bundle = bundle;
		this.created = created;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "bundle_discount_id", unique = true, nullable = false)
	public Integer getBundleDiscountId() {
		return this.bundleDiscountId;
	}

	public void setBundleDiscountId(Integer bundleDiscountId) {
		this.bundleDiscountId = bundleDiscountId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "discount_id", nullable = false)
	public Discount getDiscount() {
		return this.discount;
	}

	public void setDiscount(Discount discount) {
		this.discount = discount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bundle_id", nullable = false)
	public Bundle getBundle() {
		return this.bundle;
	}

	public void setBundle(Bundle bundle) {
		this.bundle = bundle;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
