package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * BundleFeature generated by hbm2java
 */
@Entity
@Table(name = "bundle_feature", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = {
		"bundle_id", "feature_id" }))
public class BundleFeature implements java.io.Serializable {

	private Integer bundleFeatureId;
	private Feature feature;
	private Bundle bundle;
	private Date created;

	public BundleFeature() {
	}

	public BundleFeature(Feature feature, Bundle bundle, Date created) {
		this.feature = feature;
		this.bundle = bundle;
		this.created = created;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "bundle_feature_id", unique = true, nullable = false)
	public Integer getBundleFeatureId() {
		return this.bundleFeatureId;
	}

	public void setBundleFeatureId(Integer bundleFeatureId) {
		this.bundleFeatureId = bundleFeatureId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "feature_id", nullable = false)
	public Feature getFeature() {
		return this.feature;
	}

	public void setFeature(Feature feature) {
		this.feature = feature;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bundle_id", nullable = false)
	public Bundle getBundle() {
		return this.bundle;
	}

	public void setBundle(Bundle bundle) {
		this.bundle = bundle;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
