package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * BundlePacking generated by hbm2java
 */
@Entity
@Table(name = "bundle_packing", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = "bundle_id"))
public class BundlePacking implements java.io.Serializable {

	private Integer bundlePackingId;
	private Bundle bundle;
	private BigDecimal ounces;
	private BigDecimal l;
	private BigDecimal w;
	private BigDecimal h;
	private String packing;
	private Date created;
	private Date updated;

	public BundlePacking() {
	}

	public BundlePacking(Bundle bundle, BigDecimal ounces, BigDecimal l,
			BigDecimal w, BigDecimal h, String packing, Date created,
			Date updated) {
		this.bundle = bundle;
		this.ounces = ounces;
		this.l = l;
		this.w = w;
		this.h = h;
		this.packing = packing;
		this.created = created;
		this.updated = updated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "bundle_packing_id", unique = true, nullable = false)
	public Integer getBundlePackingId() {
		return this.bundlePackingId;
	}

	public void setBundlePackingId(Integer bundlePackingId) {
		this.bundlePackingId = bundlePackingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bundle_id", unique = true, nullable = false)
	public Bundle getBundle() {
		return this.bundle;
	}

	public void setBundle(Bundle bundle) {
		this.bundle = bundle;
	}

	@Column(name = "ounces", nullable = false, precision = 6)
	public BigDecimal getOunces() {
		return this.ounces;
	}

	public void setOunces(BigDecimal ounces) {
		this.ounces = ounces;
	}

	@Column(name = "l", nullable = false, precision = 6)
	public BigDecimal getL() {
		return this.l;
	}

	public void setL(BigDecimal l) {
		this.l = l;
	}

	@Column(name = "w", nullable = false, precision = 6)
	public BigDecimal getW() {
		return this.w;
	}

	public void setW(BigDecimal w) {
		this.w = w;
	}

	@Column(name = "h", nullable = false, precision = 6)
	public BigDecimal getH() {
		return this.h;
	}

	public void setH(BigDecimal h) {
		this.h = h;
	}

	@Column(name = "packing", nullable = false, length = 9)
	public String getPacking() {
		return this.packing;
	}

	public void setPacking(String packing) {
		this.packing = packing;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 0)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

}
