package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CollectorPermission generated by hbm2java
 */
@Entity
@Table(name = "collector_permission", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = {
		"user_id", "application" }))
public class CollectorPermission implements java.io.Serializable {

	private Integer id;
	private CollectorUser collectorUser;
	private String application;
	private Date created;

	public CollectorPermission() {
	}

	public CollectorPermission(CollectorUser collectorUser, String application,
			Date created) {
		this.collectorUser = collectorUser;
		this.application = application;
		this.created = created;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public CollectorUser getCollectorUser() {
		return this.collectorUser;
	}

	public void setCollectorUser(CollectorUser collectorUser) {
		this.collectorUser = collectorUser;
	}

	@Column(name = "application", nullable = false, length = 28)
	public String getApplication() {
		return this.application;
	}

	public void setApplication(String application) {
		this.application = application;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
