package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CollectorUserIp generated by hbm2java
 */
@Entity
@Table(name = "collector_user_ip", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = {
		"user_id", "ip_address" }))
public class CollectorUserIp implements java.io.Serializable {

	private Integer id;
	private CollectorUser collectorUser;
	private String ipAddress;

	public CollectorUserIp() {
	}

	public CollectorUserIp(CollectorUser collectorUser, String ipAddress) {
		this.collectorUser = collectorUser;
		this.ipAddress = ipAddress;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public CollectorUser getCollectorUser() {
		return this.collectorUser;
	}

	public void setCollectorUser(CollectorUser collectorUser) {
		this.collectorUser = collectorUser;
	}

	@Column(name = "ip_address", nullable = false, length = 45)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

}
