package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ConcordCdrTest generated by hbm2java
 */
@Entity
@Table(name = "concord_cdr_test", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = "RecordId"))
public class ConcordCdrTest implements java.io.Serializable {

	private Integer id;
	private String salesOrgId;
	private String companyId;
	private String countryCode;
	private String areaCode;
	private String faxPhoneNumber;
	private String departmentCode;
	private String customCode1;
	private Integer customCode2;
	private String customCode3;
	private String customCode4;
	private String tollFreeFlag;
	private String userId;
	private String lastName;
	private String firstName;
	private String emailAddress;
	private Integer pageCount;
	private String date;
	private String time;
	private String timeZone;
	private String faxDestNumber;
	private String faxSourceCsid;
	private String referenceId;
	private String eventTypeDescription;
	private String subject;
	private String userField1;
	private String userField2;
	private String userField3;
	private String userField4;
	private String userField5;
	private String userField6;
	private String userField7;
	private String userField8;
	private String userField9;
	private String userField10;
	private String userField11;
	private String userField12;
	private String faxSourceSenderNumber;
	private int epochGmt;
	private Integer invoiceId;
	private String messageId;
	private String recordId;

	public ConcordCdrTest() {
	}

	public ConcordCdrTest(int epochGmt, String messageId, String recordId) {
		this.epochGmt = epochGmt;
		this.messageId = messageId;
		this.recordId = recordId;
	}

	public ConcordCdrTest(String salesOrgId, String companyId,
			String countryCode, String areaCode, String faxPhoneNumber,
			String departmentCode, String customCode1, Integer customCode2,
			String customCode3, String customCode4, String tollFreeFlag,
			String userId, String lastName, String firstName,
			String emailAddress, Integer pageCount, String date, String time,
			String timeZone, String faxDestNumber, String faxSourceCsid,
			String referenceId, String eventTypeDescription, String subject,
			String userField1, String userField2, String userField3,
			String userField4, String userField5, String userField6,
			String userField7, String userField8, String userField9,
			String userField10, String userField11, String userField12,
			String faxSourceSenderNumber, int epochGmt, Integer invoiceId,
			String messageId, String recordId) {
		this.salesOrgId = salesOrgId;
		this.companyId = companyId;
		this.countryCode = countryCode;
		this.areaCode = areaCode;
		this.faxPhoneNumber = faxPhoneNumber;
		this.departmentCode = departmentCode;
		this.customCode1 = customCode1;
		this.customCode2 = customCode2;
		this.customCode3 = customCode3;
		this.customCode4 = customCode4;
		this.tollFreeFlag = tollFreeFlag;
		this.userId = userId;
		this.lastName = lastName;
		this.firstName = firstName;
		this.emailAddress = emailAddress;
		this.pageCount = pageCount;
		this.date = date;
		this.time = time;
		this.timeZone = timeZone;
		this.faxDestNumber = faxDestNumber;
		this.faxSourceCsid = faxSourceCsid;
		this.referenceId = referenceId;
		this.eventTypeDescription = eventTypeDescription;
		this.subject = subject;
		this.userField1 = userField1;
		this.userField2 = userField2;
		this.userField3 = userField3;
		this.userField4 = userField4;
		this.userField5 = userField5;
		this.userField6 = userField6;
		this.userField7 = userField7;
		this.userField8 = userField8;
		this.userField9 = userField9;
		this.userField10 = userField10;
		this.userField11 = userField11;
		this.userField12 = userField12;
		this.faxSourceSenderNumber = faxSourceSenderNumber;
		this.epochGmt = epochGmt;
		this.invoiceId = invoiceId;
		this.messageId = messageId;
		this.recordId = recordId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "SalesOrgId", length = 16)
	public String getSalesOrgId() {
		return this.salesOrgId;
	}

	public void setSalesOrgId(String salesOrgId) {
		this.salesOrgId = salesOrgId;
	}

	@Column(name = "CompanyID", length = 16)
	public String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	@Column(name = "CountryCode", length = 8)
	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	@Column(name = "AreaCode", length = 8)
	public String getAreaCode() {
		return this.areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	@Column(name = "FaxPhoneNumber", length = 20)
	public String getFaxPhoneNumber() {
		return this.faxPhoneNumber;
	}

	public void setFaxPhoneNumber(String faxPhoneNumber) {
		this.faxPhoneNumber = faxPhoneNumber;
	}

	@Column(name = "DepartmentCode", length = 32)
	public String getDepartmentCode() {
		return this.departmentCode;
	}

	public void setDepartmentCode(String departmentCode) {
		this.departmentCode = departmentCode;
	}

	@Column(name = "CustomCode1", length = 16)
	public String getCustomCode1() {
		return this.customCode1;
	}

	public void setCustomCode1(String customCode1) {
		this.customCode1 = customCode1;
	}

	@Column(name = "CustomCode2")
	public Integer getCustomCode2() {
		return this.customCode2;
	}

	public void setCustomCode2(Integer customCode2) {
		this.customCode2 = customCode2;
	}

	@Column(name = "CustomCode3", length = 16)
	public String getCustomCode3() {
		return this.customCode3;
	}

	public void setCustomCode3(String customCode3) {
		this.customCode3 = customCode3;
	}

	@Column(name = "CustomCode4", length = 16)
	public String getCustomCode4() {
		return this.customCode4;
	}

	public void setCustomCode4(String customCode4) {
		this.customCode4 = customCode4;
	}

	@Column(name = "TollFreeFlag", length = 5)
	public String getTollFreeFlag() {
		return this.tollFreeFlag;
	}

	public void setTollFreeFlag(String tollFreeFlag) {
		this.tollFreeFlag = tollFreeFlag;
	}

	@Column(name = "UserID", length = 16)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "LastName", length = 32)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "FirstName", length = 32)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "EmailAddress", length = 128)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "PageCount")
	public Integer getPageCount() {
		return this.pageCount;
	}

	public void setPageCount(Integer pageCount) {
		this.pageCount = pageCount;
	}

	@Column(name = "Date", length = 16)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "Time", length = 16)
	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	@Column(name = "TimeZone", length = 32)
	public String getTimeZone() {
		return this.timeZone;
	}

	public void setTimeZone(String timeZone) {
		this.timeZone = timeZone;
	}

	@Column(name = "FaxDestNumber", length = 20)
	public String getFaxDestNumber() {
		return this.faxDestNumber;
	}

	public void setFaxDestNumber(String faxDestNumber) {
		this.faxDestNumber = faxDestNumber;
	}

	@Column(name = "FaxSourceCSID", length = 20)
	public String getFaxSourceCsid() {
		return this.faxSourceCsid;
	}

	public void setFaxSourceCsid(String faxSourceCsid) {
		this.faxSourceCsid = faxSourceCsid;
	}

	@Column(name = "ReferenceId", length = 20)
	public String getReferenceId() {
		return this.referenceId;
	}

	public void setReferenceId(String referenceId) {
		this.referenceId = referenceId;
	}

	@Column(name = "EventTypeDescription", length = 8)
	public String getEventTypeDescription() {
		return this.eventTypeDescription;
	}

	public void setEventTypeDescription(String eventTypeDescription) {
		this.eventTypeDescription = eventTypeDescription;
	}

	@Column(name = "Subject", length = 32)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "UserField1", length = 16)
	public String getUserField1() {
		return this.userField1;
	}

	public void setUserField1(String userField1) {
		this.userField1 = userField1;
	}

	@Column(name = "UserField2", length = 16)
	public String getUserField2() {
		return this.userField2;
	}

	public void setUserField2(String userField2) {
		this.userField2 = userField2;
	}

	@Column(name = "UserField3", length = 16)
	public String getUserField3() {
		return this.userField3;
	}

	public void setUserField3(String userField3) {
		this.userField3 = userField3;
	}

	@Column(name = "UserField4", length = 16)
	public String getUserField4() {
		return this.userField4;
	}

	public void setUserField4(String userField4) {
		this.userField4 = userField4;
	}

	@Column(name = "UserField5", length = 16)
	public String getUserField5() {
		return this.userField5;
	}

	public void setUserField5(String userField5) {
		this.userField5 = userField5;
	}

	@Column(name = "UserField6", length = 16)
	public String getUserField6() {
		return this.userField6;
	}

	public void setUserField6(String userField6) {
		this.userField6 = userField6;
	}

	@Column(name = "UserField7", length = 16)
	public String getUserField7() {
		return this.userField7;
	}

	public void setUserField7(String userField7) {
		this.userField7 = userField7;
	}

	@Column(name = "UserField8", length = 16)
	public String getUserField8() {
		return this.userField8;
	}

	public void setUserField8(String userField8) {
		this.userField8 = userField8;
	}

	@Column(name = "UserField9", length = 16)
	public String getUserField9() {
		return this.userField9;
	}

	public void setUserField9(String userField9) {
		this.userField9 = userField9;
	}

	@Column(name = "UserField10", length = 16)
	public String getUserField10() {
		return this.userField10;
	}

	public void setUserField10(String userField10) {
		this.userField10 = userField10;
	}

	@Column(name = "UserField11", length = 16)
	public String getUserField11() {
		return this.userField11;
	}

	public void setUserField11(String userField11) {
		this.userField11 = userField11;
	}

	@Column(name = "UserField12", length = 16)
	public String getUserField12() {
		return this.userField12;
	}

	public void setUserField12(String userField12) {
		this.userField12 = userField12;
	}

	@Column(name = "FaxSourceSenderNumber", length = 20)
	public String getFaxSourceSenderNumber() {
		return this.faxSourceSenderNumber;
	}

	public void setFaxSourceSenderNumber(String faxSourceSenderNumber) {
		this.faxSourceSenderNumber = faxSourceSenderNumber;
	}

	@Column(name = "epochGMT", nullable = false)
	public int getEpochGmt() {
		return this.epochGmt;
	}

	public void setEpochGmt(int epochGmt) {
		this.epochGmt = epochGmt;
	}

	@Column(name = "invoice_id")
	public Integer getInvoiceId() {
		return this.invoiceId;
	}

	public void setInvoiceId(Integer invoiceId) {
		this.invoiceId = invoiceId;
	}

	@Column(name = "MessageId", nullable = false, length = 128)
	public String getMessageId() {
		return this.messageId;
	}

	public void setMessageId(String messageId) {
		this.messageId = messageId;
	}

	@Column(name = "RecordId", unique = true, nullable = false, length = 128)
	public String getRecordId() {
		return this.recordId;
	}

	public void setRecordId(String recordId) {
		this.recordId = recordId;
	}

}
