package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "country", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Country implements java.io.Serializable {

	private Integer countryId;
	private String name;
	private String dialingCode;
	private String nationalPrefix;
	private String numericCode;
	private String alphaCode2;
	private String alphaCode3;
	private String loadzone;
	private String defaultLanguage;
	private Set<ProviderCountry> providerCountries = new HashSet<ProviderCountry>(
			0);
	private Set<Datacenter> datacenters = new HashSet<Datacenter>(0);
	private Set<CountryRegion> countryRegions = new HashSet<CountryRegion>(0);

	public Country() {
	}

	public Country(String name, String dialingCode, String nationalPrefix,
			String alphaCode2, String alphaCode3, String loadzone,
			String defaultLanguage) {
		this.name = name;
		this.dialingCode = dialingCode;
		this.nationalPrefix = nationalPrefix;
		this.alphaCode2 = alphaCode2;
		this.alphaCode3 = alphaCode3;
		this.loadzone = loadzone;
		this.defaultLanguage = defaultLanguage;
	}

	public Country(String name, String dialingCode, String nationalPrefix,
			String numericCode, String alphaCode2, String alphaCode3,
			String loadzone, String defaultLanguage,
			Set<ProviderCountry> providerCountries,
			Set<Datacenter> datacenters, Set<CountryRegion> countryRegions) {
		this.name = name;
		this.dialingCode = dialingCode;
		this.nationalPrefix = nationalPrefix;
		this.numericCode = numericCode;
		this.alphaCode2 = alphaCode2;
		this.alphaCode3 = alphaCode3;
		this.loadzone = loadzone;
		this.defaultLanguage = defaultLanguage;
		this.providerCountries = providerCountries;
		this.datacenters = datacenters;
		this.countryRegions = countryRegions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "country_id", unique = true, nullable = false)
	public Integer getCountryId() {
		return this.countryId;
	}

	public void setCountryId(Integer countryId) {
		this.countryId = countryId;
	}

	@Column(name = "name", unique = true, nullable = false, length = 80)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "dialing_code", nullable = false)
	public String getDialingCode() {
		return this.dialingCode;
	}

	public void setDialingCode(String dialingCode) {
		this.dialingCode = dialingCode;
	}

	@Column(name = "national_prefix", nullable = false)
	public String getNationalPrefix() {
		return this.nationalPrefix;
	}

	public void setNationalPrefix(String nationalPrefix) {
		this.nationalPrefix = nationalPrefix;
	}

	@Column(name = "numeric_code", length = 3)
	public String getNumericCode() {
		return this.numericCode;
	}

	public void setNumericCode(String numericCode) {
		this.numericCode = numericCode;
	}

	@Column(name = "alpha_code_2", nullable = false, length = 2)
	public String getAlphaCode2() {
		return this.alphaCode2;
	}

	public void setAlphaCode2(String alphaCode2) {
		this.alphaCode2 = alphaCode2;
	}

	@Column(name = "alpha_code_3", nullable = false, length = 3)
	public String getAlphaCode3() {
		return this.alphaCode3;
	}

	public void setAlphaCode3(String alphaCode3) {
		this.alphaCode3 = alphaCode3;
	}

	@Column(name = "loadzone", nullable = false, length = 2)
	public String getLoadzone() {
		return this.loadzone;
	}

	public void setLoadzone(String loadzone) {
		this.loadzone = loadzone;
	}

	@Column(name = "default_language", nullable = false, length = 80)
	public String getDefaultLanguage() {
		return this.defaultLanguage;
	}

	public void setDefaultLanguage(String defaultLanguage) {
		this.defaultLanguage = defaultLanguage;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
	public Set<ProviderCountry> getProviderCountries() {
		return this.providerCountries;
	}

	public void setProviderCountries(Set<ProviderCountry> providerCountries) {
		this.providerCountries = providerCountries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
	public Set<Datacenter> getDatacenters() {
		return this.datacenters;
	}

	public void setDatacenters(Set<Datacenter> datacenters) {
		this.datacenters = datacenters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
	public Set<CountryRegion> getCountryRegions() {
		return this.countryRegions;
	}

	public void setCountryRegions(Set<CountryRegion> countryRegions) {
		this.countryRegions = countryRegions;
	}

}
