package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CountryRegion generated by hbm2java
 */
@Entity
@Table(name = "country_region", catalog = "fcs")
public class CountryRegion implements java.io.Serializable {

	private Integer countryRegionId;
	private Country country;
	private String regionCode;
	private String regionName;
	private Set<RegionAreaCode> regionAreaCodes = new HashSet<RegionAreaCode>(0);

	public CountryRegion() {
	}

	public CountryRegion(Country country, String regionCode, String regionName) {
		this.country = country;
		this.regionCode = regionCode;
		this.regionName = regionName;
	}

	public CountryRegion(Country country, String regionCode, String regionName,
			Set<RegionAreaCode> regionAreaCodes) {
		this.country = country;
		this.regionCode = regionCode;
		this.regionName = regionName;
		this.regionAreaCodes = regionAreaCodes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "country_region_id", unique = true, nullable = false)
	public Integer getCountryRegionId() {
		return this.countryRegionId;
	}

	public void setCountryRegionId(Integer countryRegionId) {
		this.countryRegionId = countryRegionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "country_id", nullable = false)
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@Column(name = "region_code", nullable = false, length = 3)
	public String getRegionCode() {
		return this.regionCode;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}

	@Column(name = "region_name", nullable = false, length = 28)
	public String getRegionName() {
		return this.regionName;
	}

	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "countryRegion")
	public Set<RegionAreaCode> getRegionAreaCodes() {
		return this.regionAreaCodes;
	}

	public void setRegionAreaCodes(Set<RegionAreaCode> regionAreaCodes) {
		this.regionAreaCodes = regionAreaCodes;
	}

}
