package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CustomerContact generated by hbm2java
 */
@Entity
@Table(name = "customer_contact", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = {
		"customer_id", "contact_id" }))
public class CustomerContact implements java.io.Serializable {

	private Integer customerContactId;
	private EntityContact entityContact;
	private int customerId;

	public CustomerContact() {
	}

	public CustomerContact(EntityContact entityContact, int customerId) {
		this.entityContact = entityContact;
		this.customerId = customerId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "customer_contact_id", unique = true, nullable = false)
	public Integer getCustomerContactId() {
		return this.customerContactId;
	}

	public void setCustomerContactId(Integer customerContactId) {
		this.customerContactId = customerContactId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contact_id", nullable = false)
	public EntityContact getEntityContact() {
		return this.entityContact;
	}

	public void setEntityContact(EntityContact entityContact) {
		this.entityContact = entityContact;
	}

	@Column(name = "customer_id", nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

}
