package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CustomerAddress generated by hbm2java
 */
@Entity
@Table(name = "customer_address", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = {
		"customer_id", "address_id" }))
public class CustomerAddress implements java.io.Serializable {

	private Integer customerAddressId;
	private EntityAddress entityAddress;
	private int customerId;

	public CustomerAddress() {
	}

	public CustomerAddress(EntityAddress entityAddress, int customerId) {
		this.entityAddress = entityAddress;
		this.customerId = customerId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "customer_address_id", unique = true, nullable = false)
	public Integer getCustomerAddressId() {
		return this.customerAddressId;
	}

	public void setCustomerAddressId(Integer customerAddressId) {
		this.customerAddressId = customerAddressId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "address_id", nullable = false)
	public EntityAddress getEntityAddress() {
		return this.entityAddress;
	}

	public void setEntityAddress(EntityAddress entityAddress) {
		this.entityAddress = entityAddress;
	}

	@Column(name = "customer_id", nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

}
