package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Datacenter generated by hbm2java
 */
@Entity
@Table(name = "datacenter", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = {
		"country_id", "state_prov", "location" }))
public class Datacenter implements java.io.Serializable {

	private Integer datacenterId;
	private Country country;
	private String stateProv;
	private String location;

	public Datacenter() {
	}

	public Datacenter(Country country, String stateProv, String location) {
		this.country = country;
		this.stateProv = stateProv;
		this.location = location;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "datacenter_id", unique = true, nullable = false)
	public Integer getDatacenterId() {
		return this.datacenterId;
	}

	public void setDatacenterId(Integer datacenterId) {
		this.datacenterId = datacenterId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "country_id", nullable = false)
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@Column(name = "state_prov", nullable = false, length = 10)
	public String getStateProv() {
		return this.stateProv;
	}

	public void setStateProv(String stateProv) {
		this.stateProv = stateProv;
	}

	@Column(name = "location", nullable = false, length = 3)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

}
