package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DiscountCategory generated by hbm2java
 */
@Entity
@Table(name = "discount_category", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class DiscountCategory implements java.io.Serializable {

	private Integer discountCategoryId;
	private String name;
	private Set<Discount> discounts = new HashSet<Discount>(0);
	private Set<BundleCategory> bundleCategories = new HashSet<BundleCategory>(
			0);
	private Set<DiscountLimit> discountLimits = new HashSet<DiscountLimit>(0);

	public DiscountCategory() {
	}

	public DiscountCategory(String name) {
		this.name = name;
	}

	public DiscountCategory(String name, Set<Discount> discounts,
			Set<BundleCategory> bundleCategories,
			Set<DiscountLimit> discountLimits) {
		this.name = name;
		this.discounts = discounts;
		this.bundleCategories = bundleCategories;
		this.discountLimits = discountLimits;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "discount_category_id", unique = true, nullable = false)
	public Integer getDiscountCategoryId() {
		return this.discountCategoryId;
	}

	public void setDiscountCategoryId(Integer discountCategoryId) {
		this.discountCategoryId = discountCategoryId;
	}

	@Column(name = "name", unique = true, nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "discountCategory")
	public Set<Discount> getDiscounts() {
		return this.discounts;
	}

	public void setDiscounts(Set<Discount> discounts) {
		this.discounts = discounts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "discountCategory")
	public Set<BundleCategory> getBundleCategories() {
		return this.bundleCategories;
	}

	public void setBundleCategories(Set<BundleCategory> bundleCategories) {
		this.bundleCategories = bundleCategories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "discountCategory")
	public Set<DiscountLimit> getDiscountLimits() {
		return this.discountLimits;
	}

	public void setDiscountLimits(Set<DiscountLimit> discountLimits) {
		this.discountLimits = discountLimits;
	}

}
