package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DiscountType generated by hbm2java
 */
@Entity
@Table(name = "discount_type", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class DiscountType implements java.io.Serializable {

	private Integer discountTypeId;
	private String name;
	private Set<ResellerDiscount> resellerDiscounts = new HashSet<ResellerDiscount>(
			0);
	private Set<OrderDiscount> orderDiscounts = new HashSet<OrderDiscount>(0);

	public DiscountType() {
	}

	public DiscountType(String name) {
		this.name = name;
	}

	public DiscountType(String name, Set<ResellerDiscount> resellerDiscounts,
			Set<OrderDiscount> orderDiscounts) {
		this.name = name;
		this.resellerDiscounts = resellerDiscounts;
		this.orderDiscounts = orderDiscounts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "discount_type_id", unique = true, nullable = false)
	public Integer getDiscountTypeId() {
		return this.discountTypeId;
	}

	public void setDiscountTypeId(Integer discountTypeId) {
		this.discountTypeId = discountTypeId;
	}

	@Column(name = "name", unique = true, nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "discountType")
	public Set<ResellerDiscount> getResellerDiscounts() {
		return this.resellerDiscounts;
	}

	public void setResellerDiscounts(Set<ResellerDiscount> resellerDiscounts) {
		this.resellerDiscounts = resellerDiscounts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "discountType")
	public Set<OrderDiscount> getOrderDiscounts() {
		return this.orderDiscounts;
	}

	public void setOrderDiscounts(Set<OrderDiscount> orderDiscounts) {
		this.orderDiscounts = orderDiscounts;
	}

}
