package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * EntityContact generated by hbm2java
 */
@Entity
@Table(name = "entity_contact", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = {
		"first_name", "last_name", "email" }))
public class EntityContact implements java.io.Serializable {

	private Integer entityContactId;
	private Long netsuiteId;
	private String role;
	private String firstName;
	private String lastName;
	private String email;
	private String phone;
	private Integer extension;
	private Date created;
	private Date updated;
	private Set<CustomerContact> customerContacts = new HashSet<CustomerContact>(
			0);
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public EntityContact() {
	}

	public EntityContact(String role, String firstName, String lastName,
			String email, String phone, Date created, Date updated) {
		this.role = role;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.phone = phone;
		this.created = created;
		this.updated = updated;
	}

	public EntityContact(Long netsuiteId, String role, String firstName,
			String lastName, String email, String phone, Integer extension,
			Date created, Date updated, Set<CustomerContact> customerContacts,
			Set<Orders> orderses) {
		this.netsuiteId = netsuiteId;
		this.role = role;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.phone = phone;
		this.extension = extension;
		this.created = created;
		this.updated = updated;
		this.customerContacts = customerContacts;
		this.orderses = orderses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "entity_contact_id", unique = true, nullable = false)
	public Integer getEntityContactId() {
		return this.entityContactId;
	}

	public void setEntityContactId(Integer entityContactId) {
		this.entityContactId = entityContactId;
	}

	@Column(name = "netsuite_id")
	public Long getNetsuiteId() {
		return this.netsuiteId;
	}

	public void setNetsuiteId(Long netsuiteId) {
		this.netsuiteId = netsuiteId;
	}

	@Column(name = "role", nullable = false, length = 7)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "first_name", nullable = false, length = 80)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", nullable = false, length = 80)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "email", nullable = false, length = 128)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", nullable = false, length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "extension")
	public Integer getExtension() {
		return this.extension;
	}

	public void setExtension(Integer extension) {
		this.extension = extension;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 0)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entityContact")
	public Set<CustomerContact> getCustomerContacts() {
		return this.customerContacts;
	}

	public void setCustomerContacts(Set<CustomerContact> customerContacts) {
		this.customerContacts = customerContacts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entityContact")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
