package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Feature generated by hbm2java
 */
@Entity
@Table(name = "feature", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Feature implements java.io.Serializable {

	private Integer featureId;
	private String name;
	private String description;
	private Date created;
	private Date updated;
	private Set<BundleFeature> bundleFeatures = new HashSet<BundleFeature>(0);
	private Set<Perm> perms = new HashSet<Perm>(0);
	private Set<LicenseFeature> licenseFeatures = new HashSet<LicenseFeature>(0);

	public Feature() {
	}

	public Feature(String name, String description, Date created, Date updated) {
		this.name = name;
		this.description = description;
		this.created = created;
		this.updated = updated;
	}

	public Feature(String name, String description, Date created, Date updated,
			Set<BundleFeature> bundleFeatures, Set<Perm> perms,
			Set<LicenseFeature> licenseFeatures) {
		this.name = name;
		this.description = description;
		this.created = created;
		this.updated = updated;
		this.bundleFeatures = bundleFeatures;
		this.perms = perms;
		this.licenseFeatures = licenseFeatures;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "feature_id", unique = true, nullable = false)
	public Integer getFeatureId() {
		return this.featureId;
	}

	public void setFeatureId(Integer featureId) {
		this.featureId = featureId;
	}

	@Column(name = "name", unique = true, nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false, length = 16777215)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 0)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "feature")
	public Set<BundleFeature> getBundleFeatures() {
		return this.bundleFeatures;
	}

	public void setBundleFeatures(Set<BundleFeature> bundleFeatures) {
		this.bundleFeatures = bundleFeatures;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "feature")
	public Set<Perm> getPerms() {
		return this.perms;
	}

	public void setPerms(Set<Perm> perms) {
		this.perms = perms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "feature")
	public Set<LicenseFeature> getLicenseFeatures() {
		return this.licenseFeatures;
	}

	public void setLicenseFeatures(Set<LicenseFeature> licenseFeatures) {
		this.licenseFeatures = licenseFeatures;
	}

}
