package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * IntranetSetting generated by hbm2java
 */
@Entity
@Table(name = "intranet_setting", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = "setting"))
public class IntranetSetting implements java.io.Serializable {

	private Integer intranetSettingId;
	private String setting;
	private String value;

	public IntranetSetting() {
	}

	public IntranetSetting(String setting, String value) {
		this.setting = setting;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "intranet_setting_id", unique = true, nullable = false)
	public Integer getIntranetSettingId() {
		return this.intranetSettingId;
	}

	public void setIntranetSettingId(Integer intranetSettingId) {
		this.intranetSettingId = intranetSettingId;
	}

	@Column(name = "setting", unique = true, nullable = false, length = 128)
	public String getSetting() {
		return this.setting;
	}

	public void setSetting(String setting) {
		this.setting = setting;
	}

	@Column(name = "value", nullable = false, length = 128)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
