package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * IntranetPermission generated by hbm2java
 */
@Entity
@Table(name = "intranet_permission", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class IntranetPermission implements java.io.Serializable {

	private Integer intranetPermissionId;
	private IntranetPermission intranetPermission;
	private String name;
	private String description;
	private String access;
	private Set<IntranetRoleXref> intranetRoleXrefs = new HashSet<IntranetRoleXref>(
			0);
	private Set<IntranetUserPermissionXref> intranetUserPermissionXrefs = new HashSet<IntranetUserPermissionXref>(
			0);
	private Set<IntranetPermission> intranetPermissions = new HashSet<IntranetPermission>(
			0);

	public IntranetPermission() {
	}

	public IntranetPermission(String name, String description, String access) {
		this.name = name;
		this.description = description;
		this.access = access;
	}

	public IntranetPermission(IntranetPermission intranetPermission,
			String name, String description, String access,
			Set<IntranetRoleXref> intranetRoleXrefs,
			Set<IntranetUserPermissionXref> intranetUserPermissionXrefs,
			Set<IntranetPermission> intranetPermissions) {
		this.intranetPermission = intranetPermission;
		this.name = name;
		this.description = description;
		this.access = access;
		this.intranetRoleXrefs = intranetRoleXrefs;
		this.intranetUserPermissionXrefs = intranetUserPermissionXrefs;
		this.intranetPermissions = intranetPermissions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "intranet_permission_id", unique = true, nullable = false)
	public Integer getIntranetPermissionId() {
		return this.intranetPermissionId;
	}

	public void setIntranetPermissionId(Integer intranetPermissionId) {
		this.intranetPermissionId = intranetPermissionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id")
	public IntranetPermission getIntranetPermission() {
		return this.intranetPermission;
	}

	public void setIntranetPermission(IntranetPermission intranetPermission) {
		this.intranetPermission = intranetPermission;
	}

	@Column(name = "name", unique = true, nullable = false, length = 36)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false, length = 128)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "access", nullable = false, length = 3)
	public String getAccess() {
		return this.access;
	}

	public void setAccess(String access) {
		this.access = access;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "intranetPermission")
	public Set<IntranetRoleXref> getIntranetRoleXrefs() {
		return this.intranetRoleXrefs;
	}

	public void setIntranetRoleXrefs(Set<IntranetRoleXref> intranetRoleXrefs) {
		this.intranetRoleXrefs = intranetRoleXrefs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "intranetPermission")
	public Set<IntranetUserPermissionXref> getIntranetUserPermissionXrefs() {
		return this.intranetUserPermissionXrefs;
	}

	public void setIntranetUserPermissionXrefs(
			Set<IntranetUserPermissionXref> intranetUserPermissionXrefs) {
		this.intranetUserPermissionXrefs = intranetUserPermissionXrefs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "intranetPermission")
	public Set<IntranetPermission> getIntranetPermissions() {
		return this.intranetPermissions;
	}

	public void setIntranetPermissions(
			Set<IntranetPermission> intranetPermissions) {
		this.intranetPermissions = intranetPermissions;
	}

}
