package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * IntranetRole generated by hbm2java
 */
@Entity
@Table(name = "intranet_role", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class IntranetRole implements java.io.Serializable {

	private Integer intranetRoleId;
	private String name;
	private String description;
	private Date created;
	private Date updated;
	private Set<IntranetUserRoleXref> intranetUserRoleXrefs = new HashSet<IntranetUserRoleXref>(
			0);
	private Set<IntranetRoleXref> intranetRoleXrefs = new HashSet<IntranetRoleXref>(
			0);
	private Set<PromoRole> promoRoles = new HashSet<PromoRole>(0);

	public IntranetRole() {
	}

	public IntranetRole(String name, String description, Date created,
			Date updated) {
		this.name = name;
		this.description = description;
		this.created = created;
		this.updated = updated;
	}

	public IntranetRole(String name, String description, Date created,
			Date updated, Set<IntranetUserRoleXref> intranetUserRoleXrefs,
			Set<IntranetRoleXref> intranetRoleXrefs, Set<PromoRole> promoRoles) {
		this.name = name;
		this.description = description;
		this.created = created;
		this.updated = updated;
		this.intranetUserRoleXrefs = intranetUserRoleXrefs;
		this.intranetRoleXrefs = intranetRoleXrefs;
		this.promoRoles = promoRoles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "intranet_role_id", unique = true, nullable = false)
	public Integer getIntranetRoleId() {
		return this.intranetRoleId;
	}

	public void setIntranetRoleId(Integer intranetRoleId) {
		this.intranetRoleId = intranetRoleId;
	}

	@Column(name = "name", unique = true, nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false, length = 16777215)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 0)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "intranetRole")
	public Set<IntranetUserRoleXref> getIntranetUserRoleXrefs() {
		return this.intranetUserRoleXrefs;
	}

	public void setIntranetUserRoleXrefs(
			Set<IntranetUserRoleXref> intranetUserRoleXrefs) {
		this.intranetUserRoleXrefs = intranetUserRoleXrefs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "intranetRole")
	public Set<IntranetRoleXref> getIntranetRoleXrefs() {
		return this.intranetRoleXrefs;
	}

	public void setIntranetRoleXrefs(Set<IntranetRoleXref> intranetRoleXrefs) {
		this.intranetRoleXrefs = intranetRoleXrefs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "intranetRole")
	public Set<PromoRole> getPromoRoles() {
		return this.promoRoles;
	}

	public void setPromoRoles(Set<PromoRole> promoRoles) {
		this.promoRoles = promoRoles;
	}

}
