package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * IntranetSearchable generated by hbm2java
 */
@Entity
@Table(name = "intranet_searchable", catalog = "fcs")
public class IntranetSearchable implements java.io.Serializable {

	private Integer intranetSearchableId;
	private String mode;
	private String format;
	private String action;
	private String param;

	public IntranetSearchable() {
	}

	public IntranetSearchable(String mode, String format, String action,
			String param) {
		this.mode = mode;
		this.format = format;
		this.action = action;
		this.param = param;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "intranet_searchable_id", unique = true, nullable = false)
	public Integer getIntranetSearchableId() {
		return this.intranetSearchableId;
	}

	public void setIntranetSearchableId(Integer intranetSearchableId) {
		this.intranetSearchableId = intranetSearchableId;
	}

	@Column(name = "mode", nullable = false, length = 36)
	public String getMode() {
		return this.mode;
	}

	public void setMode(String mode) {
		this.mode = mode;
	}

	@Column(name = "format", nullable = false, length = 72)
	public String getFormat() {
		return this.format;
	}

	public void setFormat(String format) {
		this.format = format;
	}

	@Column(name = "action", nullable = false, length = 36)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "param", nullable = false, length = 36)
	public String getParam() {
		return this.param;
	}

	public void setParam(String param) {
		this.param = param;
	}

}
