package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * IntranetUser generated by hbm2java
 */
@Entity
@Table(name = "intranet_user", catalog = "fcs", uniqueConstraints = {
		@UniqueConstraint(columnNames = "email"),
		@UniqueConstraint(columnNames = "username") })
public class IntranetUser implements java.io.Serializable {

	private Integer intranetUserId;
	private String username;
	private String firstName;
	private String lastName;
	private String email;
	private String password;
	private String salt;
	private int passwordUpdated;
	private boolean lockout;
	private boolean disabled;
	private Date disabledDate;
	private String lastLoginIp;
	private Date created;
	private Date updated;
	private Set<IntranetAudit> intranetAudits = new HashSet<IntranetAudit>(0);
	private Set<IntranetUserPermissionXref> intranetUserPermissionXrefs = new HashSet<IntranetUserPermissionXref>(
			0);
	private Set<IntranetUserRoleXref> intranetUserRoleXrefs = new HashSet<IntranetUserRoleXref>(
			0);

	public IntranetUser() {
	}

	public IntranetUser(String username, String firstName, String lastName,
			String email, String password, String salt, int passwordUpdated,
			boolean lockout, boolean disabled, Date disabledDate,
			String lastLoginIp, Date created, Date updated) {
		this.username = username;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.password = password;
		this.salt = salt;
		this.passwordUpdated = passwordUpdated;
		this.lockout = lockout;
		this.disabled = disabled;
		this.disabledDate = disabledDate;
		this.lastLoginIp = lastLoginIp;
		this.created = created;
		this.updated = updated;
	}

	public IntranetUser(String username, String firstName, String lastName,
			String email, String password, String salt, int passwordUpdated,
			boolean lockout, boolean disabled, Date disabledDate,
			String lastLoginIp, Date created, Date updated,
			Set<IntranetAudit> intranetAudits,
			Set<IntranetUserPermissionXref> intranetUserPermissionXrefs,
			Set<IntranetUserRoleXref> intranetUserRoleXrefs) {
		this.username = username;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.password = password;
		this.salt = salt;
		this.passwordUpdated = passwordUpdated;
		this.lockout = lockout;
		this.disabled = disabled;
		this.disabledDate = disabledDate;
		this.lastLoginIp = lastLoginIp;
		this.created = created;
		this.updated = updated;
		this.intranetAudits = intranetAudits;
		this.intranetUserPermissionXrefs = intranetUserPermissionXrefs;
		this.intranetUserRoleXrefs = intranetUserRoleXrefs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "intranet_user_id", unique = true, nullable = false)
	public Integer getIntranetUserId() {
		return this.intranetUserId;
	}

	public void setIntranetUserId(Integer intranetUserId) {
		this.intranetUserId = intranetUserId;
	}

	@Column(name = "username", unique = true, nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "first_name", nullable = false, length = 80)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", nullable = false, length = 80)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "email", unique = true, nullable = false, length = 128)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 46)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "salt", nullable = false, length = 16)
	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	@Column(name = "password_updated", nullable = false)
	public int getPasswordUpdated() {
		return this.passwordUpdated;
	}

	public void setPasswordUpdated(int passwordUpdated) {
		this.passwordUpdated = passwordUpdated;
	}

	@Column(name = "lockout", nullable = false)
	public boolean isLockout() {
		return this.lockout;
	}

	public void setLockout(boolean lockout) {
		this.lockout = lockout;
	}

	@Column(name = "disabled", nullable = false)
	public boolean isDisabled() {
		return this.disabled;
	}

	public void setDisabled(boolean disabled) {
		this.disabled = disabled;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "disabled_date", nullable = false, length = 0)
	public Date getDisabledDate() {
		return this.disabledDate;
	}

	public void setDisabledDate(Date disabledDate) {
		this.disabledDate = disabledDate;
	}

	@Column(name = "last_login_ip", nullable = false, length = 45)
	public String getLastLoginIp() {
		return this.lastLoginIp;
	}

	public void setLastLoginIp(String lastLoginIp) {
		this.lastLoginIp = lastLoginIp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 0)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "intranetUser")
	public Set<IntranetAudit> getIntranetAudits() {
		return this.intranetAudits;
	}

	public void setIntranetAudits(Set<IntranetAudit> intranetAudits) {
		this.intranetAudits = intranetAudits;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "intranetUser")
	public Set<IntranetUserPermissionXref> getIntranetUserPermissionXrefs() {
		return this.intranetUserPermissionXrefs;
	}

	public void setIntranetUserPermissionXrefs(
			Set<IntranetUserPermissionXref> intranetUserPermissionXrefs) {
		this.intranetUserPermissionXrefs = intranetUserPermissionXrefs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "intranetUser")
	public Set<IntranetUserRoleXref> getIntranetUserRoleXrefs() {
		return this.intranetUserRoleXrefs;
	}

	public void setIntranetUserRoleXrefs(
			Set<IntranetUserRoleXref> intranetUserRoleXrefs) {
		this.intranetUserRoleXrefs = intranetUserRoleXrefs;
	}

}
