package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * IntranetUserRoleXref generated by hbm2java
 */
@Entity
@Table(name = "intranet_user_role_xref", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = {
		"intranet_user_id", "role_id" }))
public class IntranetUserRoleXref implements java.io.Serializable {

	private Integer intranetUserRoleXrefId;
	private IntranetUser intranetUser;
	private IntranetRole intranetRole;
	private Date updated;

	public IntranetUserRoleXref() {
	}

	public IntranetUserRoleXref(IntranetUser intranetUser,
			IntranetRole intranetRole, Date updated) {
		this.intranetUser = intranetUser;
		this.intranetRole = intranetRole;
		this.updated = updated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "intranet_user_role_xref_id", unique = true, nullable = false)
	public Integer getIntranetUserRoleXrefId() {
		return this.intranetUserRoleXrefId;
	}

	public void setIntranetUserRoleXrefId(Integer intranetUserRoleXrefId) {
		this.intranetUserRoleXrefId = intranetUserRoleXrefId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intranet_user_id", nullable = false)
	public IntranetUser getIntranetUser() {
		return this.intranetUser;
	}

	public void setIntranetUser(IntranetUser intranetUser) {
		this.intranetUser = intranetUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false)
	public IntranetRole getIntranetRole() {
		return this.intranetRole;
	}

	public void setIntranetRole(IntranetRole intranetRole) {
		this.intranetRole = intranetRole;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 0)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

}
