package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IntranetAudit generated by hbm2java
 */
@Entity
@Table(name = "intranet_audit", catalog = "fcs")
public class IntranetAudit implements java.io.Serializable {

	private Integer intranetAuditId;
	private IntranetUser intranetUser;
	private Integer customerId;
	private Integer serverId;
	private String module;
	private String function;
	private String audit;
	private Date updated;

	public IntranetAudit() {
	}

	public IntranetAudit(IntranetUser intranetUser, String module,
			String function, String audit, Date updated) {
		this.intranetUser = intranetUser;
		this.module = module;
		this.function = function;
		this.audit = audit;
		this.updated = updated;
	}

	public IntranetAudit(IntranetUser intranetUser, Integer customerId,
			Integer serverId, String module, String function, String audit,
			Date updated) {
		this.intranetUser = intranetUser;
		this.customerId = customerId;
		this.serverId = serverId;
		this.module = module;
		this.function = function;
		this.audit = audit;
		this.updated = updated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "intranet_audit_id", unique = true, nullable = false)
	public Integer getIntranetAuditId() {
		return this.intranetAuditId;
	}

	public void setIntranetAuditId(Integer intranetAuditId) {
		this.intranetAuditId = intranetAuditId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intranet_user_id", nullable = false)
	public IntranetUser getIntranetUser() {
		return this.intranetUser;
	}

	public void setIntranetUser(IntranetUser intranetUser) {
		this.intranetUser = intranetUser;
	}

	@Column(name = "customer_id")
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "server_id")
	public Integer getServerId() {
		return this.serverId;
	}

	public void setServerId(Integer serverId) {
		this.serverId = serverId;
	}

	@Column(name = "module", nullable = false, length = 36)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "function", nullable = false, length = 128)
	public String getFunction() {
		return this.function;
	}

	public void setFunction(String function) {
		this.function = function;
	}

	@Column(name = "audit", nullable = false, length = 128)
	public String getAudit() {
		return this.audit;
	}

	public void setAudit(String audit) {
		this.audit = audit;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 0)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

}
