package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * IntranetRoleXref generated by hbm2java
 */
@Entity
@Table(name = "intranet_role_xref", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = {
		"role_id", "permission_id" }))
public class IntranetRoleXref implements java.io.Serializable {

	private Integer intranetRoleXrefId;
	private IntranetRole intranetRole;
	private IntranetPermission intranetPermission;
	private String access;

	public IntranetRoleXref() {
	}

	public IntranetRoleXref(IntranetRole intranetRole,
			IntranetPermission intranetPermission, String access) {
		this.intranetRole = intranetRole;
		this.intranetPermission = intranetPermission;
		this.access = access;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "intranet_role_xref_id", unique = true, nullable = false)
	public Integer getIntranetRoleXrefId() {
		return this.intranetRoleXrefId;
	}

	public void setIntranetRoleXrefId(Integer intranetRoleXrefId) {
		this.intranetRoleXrefId = intranetRoleXrefId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false)
	public IntranetRole getIntranetRole() {
		return this.intranetRole;
	}

	public void setIntranetRole(IntranetRole intranetRole) {
		this.intranetRole = intranetRole;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "permission_id", nullable = false)
	public IntranetPermission getIntranetPermission() {
		return this.intranetPermission;
	}

	public void setIntranetPermission(IntranetPermission intranetPermission) {
		this.intranetPermission = intranetPermission;
	}

	@Column(name = "access", nullable = false, length = 3)
	public String getAccess() {
		return this.access;
	}

	public void setAccess(String access) {
		this.access = access;
	}

}
