package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IntranetLog generated by hbm2java
 */
@Entity
@Table(name = "intranet_log", catalog = "fcs")
public class IntranetLog implements java.io.Serializable {

	private Integer intranetLogId;
	private String intranetUser;
	private String module;
	private String level;
	private String function;
	private String message;
	private String ipAddress;
	private Date updated;

	public IntranetLog() {
	}

	public IntranetLog(String intranetUser, String module, String level,
			String function, String message, String ipAddress, Date updated) {
		this.intranetUser = intranetUser;
		this.module = module;
		this.level = level;
		this.function = function;
		this.message = message;
		this.ipAddress = ipAddress;
		this.updated = updated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "intranet_log_id", unique = true, nullable = false)
	public Integer getIntranetLogId() {
		return this.intranetLogId;
	}

	public void setIntranetLogId(Integer intranetLogId) {
		this.intranetLogId = intranetLogId;
	}

	@Column(name = "intranet_user", nullable = false, length = 50)
	public String getIntranetUser() {
		return this.intranetUser;
	}

	public void setIntranetUser(String intranetUser) {
		this.intranetUser = intranetUser;
	}

	@Column(name = "module", nullable = false, length = 36)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "level", nullable = false, length = 16)
	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	@Column(name = "function", nullable = false, length = 128)
	public String getFunction() {
		return this.function;
	}

	public void setFunction(String function) {
		this.function = function;
	}

	@Column(name = "message", nullable = false, length = 16777215)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "ip_address", nullable = false, length = 45)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 0)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

}
