package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * LicensePerm generated by hbm2java
 */
@Entity
@Table(name = "license_perm", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = {
		"license_type_id", "perm_id" }))
public class LicensePerm implements java.io.Serializable {

	private Integer licensePermId;
	private LicenseType licenseType;
	private Perm perm;
	private String type;

	public LicensePerm() {
	}

	public LicensePerm(LicenseType licenseType, Perm perm, String type) {
		this.licenseType = licenseType;
		this.perm = perm;
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "license_perm_id", unique = true, nullable = false)
	public Integer getLicensePermId() {
		return this.licensePermId;
	}

	public void setLicensePermId(Integer licensePermId) {
		this.licensePermId = licensePermId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "license_type_id", nullable = false)
	public LicenseType getLicenseType() {
		return this.licenseType;
	}

	public void setLicenseType(LicenseType licenseType) {
		this.licenseType = licenseType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "perm_id", nullable = false)
	public Perm getPerm() {
		return this.perm;
	}

	public void setPerm(Perm perm) {
		this.perm = perm;
	}

	@Column(name = "type", nullable = false, length = 5)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
