package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * LicenseType generated by hbm2java
 */
@Entity
@Table(name = "license_type", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class LicenseType implements java.io.Serializable {

	private Integer licenseTypeId;
	private String name;
	private String label;
	private Set<Role> roles = new HashSet<Role>(0);
	private Set<LicensePrereq> licensePrereqsForPrereqLicenseTypeId = new HashSet<LicensePrereq>(
			0);
	private Set<LicensePrereq> licensePrereqsForLicenseTypeId = new HashSet<LicensePrereq>(
			0);
	private Set<LicenseFeature> licenseFeatures = new HashSet<LicenseFeature>(0);
	private Set<BundleLicense> bundleLicenses = new HashSet<BundleLicense>(0);
	private Set<HudLicenseMap> hudLicenseMaps = new HashSet<HudLicenseMap>(0);
	private Set<ServerLicense> serverLicenses = new HashSet<ServerLicense>(0);
	private Set<UserLicense> userLicenses = new HashSet<UserLicense>(0);
	private Set<LicensePerm> licensePerms = new HashSet<LicensePerm>(0);

	public LicenseType() {
	}

	public LicenseType(String name, String label) {
		this.name = name;
		this.label = label;
	}

	public LicenseType(String name, String label, Set<Role> roles,
			Set<LicensePrereq> licensePrereqsForPrereqLicenseTypeId,
			Set<LicensePrereq> licensePrereqsForLicenseTypeId,
			Set<LicenseFeature> licenseFeatures,
			Set<BundleLicense> bundleLicenses,
			Set<HudLicenseMap> hudLicenseMaps,
			Set<ServerLicense> serverLicenses, Set<UserLicense> userLicenses,
			Set<LicensePerm> licensePerms) {
		this.name = name;
		this.label = label;
		this.roles = roles;
		this.licensePrereqsForPrereqLicenseTypeId = licensePrereqsForPrereqLicenseTypeId;
		this.licensePrereqsForLicenseTypeId = licensePrereqsForLicenseTypeId;
		this.licenseFeatures = licenseFeatures;
		this.bundleLicenses = bundleLicenses;
		this.hudLicenseMaps = hudLicenseMaps;
		this.serverLicenses = serverLicenses;
		this.userLicenses = userLicenses;
		this.licensePerms = licensePerms;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "license_type_id", unique = true, nullable = false)
	public Integer getLicenseTypeId() {
		return this.licenseTypeId;
	}

	public void setLicenseTypeId(Integer licenseTypeId) {
		this.licenseTypeId = licenseTypeId;
	}

	@Column(name = "name", unique = true, nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "label", nullable = false)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licenseType")
	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licenseTypeByPrereqLicenseTypeId")
	public Set<LicensePrereq> getLicensePrereqsForPrereqLicenseTypeId() {
		return this.licensePrereqsForPrereqLicenseTypeId;
	}

	public void setLicensePrereqsForPrereqLicenseTypeId(
			Set<LicensePrereq> licensePrereqsForPrereqLicenseTypeId) {
		this.licensePrereqsForPrereqLicenseTypeId = licensePrereqsForPrereqLicenseTypeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licenseTypeByLicenseTypeId")
	public Set<LicensePrereq> getLicensePrereqsForLicenseTypeId() {
		return this.licensePrereqsForLicenseTypeId;
	}

	public void setLicensePrereqsForLicenseTypeId(
			Set<LicensePrereq> licensePrereqsForLicenseTypeId) {
		this.licensePrereqsForLicenseTypeId = licensePrereqsForLicenseTypeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licenseType")
	public Set<LicenseFeature> getLicenseFeatures() {
		return this.licenseFeatures;
	}

	public void setLicenseFeatures(Set<LicenseFeature> licenseFeatures) {
		this.licenseFeatures = licenseFeatures;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licenseType")
	public Set<BundleLicense> getBundleLicenses() {
		return this.bundleLicenses;
	}

	public void setBundleLicenses(Set<BundleLicense> bundleLicenses) {
		this.bundleLicenses = bundleLicenses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licenseType")
	public Set<HudLicenseMap> getHudLicenseMaps() {
		return this.hudLicenseMaps;
	}

	public void setHudLicenseMaps(Set<HudLicenseMap> hudLicenseMaps) {
		this.hudLicenseMaps = hudLicenseMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licenseType")
	public Set<ServerLicense> getServerLicenses() {
		return this.serverLicenses;
	}

	public void setServerLicenses(Set<ServerLicense> serverLicenses) {
		this.serverLicenses = serverLicenses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licenseType")
	public Set<UserLicense> getUserLicenses() {
		return this.userLicenses;
	}

	public void setUserLicenses(Set<UserLicense> userLicenses) {
		this.userLicenses = userLicenses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licenseType")
	public Set<LicensePerm> getLicensePerms() {
		return this.licensePerms;
	}

	public void setLicensePerms(Set<LicensePerm> licensePerms) {
		this.licensePerms = licensePerms;
	}

}
