package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * LicensePrereq generated by hbm2java
 */
@Entity
@Table(name = "license_prereq", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = {
		"license_type_id", "prereq_license_type_id" }))
public class LicensePrereq implements java.io.Serializable {

	private Integer licensePrereqId;
	private LicenseType licenseTypeByLicenseTypeId;
	private LicenseType licenseTypeByPrereqLicenseTypeId;

	public LicensePrereq() {
	}

	public LicensePrereq(LicenseType licenseTypeByLicenseTypeId,
			LicenseType licenseTypeByPrereqLicenseTypeId) {
		this.licenseTypeByLicenseTypeId = licenseTypeByLicenseTypeId;
		this.licenseTypeByPrereqLicenseTypeId = licenseTypeByPrereqLicenseTypeId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "license_prereq_id", unique = true, nullable = false)
	public Integer getLicensePrereqId() {
		return this.licensePrereqId;
	}

	public void setLicensePrereqId(Integer licensePrereqId) {
		this.licensePrereqId = licensePrereqId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "license_type_id", nullable = false)
	public LicenseType getLicenseTypeByLicenseTypeId() {
		return this.licenseTypeByLicenseTypeId;
	}

	public void setLicenseTypeByLicenseTypeId(
			LicenseType licenseTypeByLicenseTypeId) {
		this.licenseTypeByLicenseTypeId = licenseTypeByLicenseTypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prereq_license_type_id", nullable = false)
	public LicenseType getLicenseTypeByPrereqLicenseTypeId() {
		return this.licenseTypeByPrereqLicenseTypeId;
	}

	public void setLicenseTypeByPrereqLicenseTypeId(
			LicenseType licenseTypeByPrereqLicenseTypeId) {
		this.licenseTypeByPrereqLicenseTypeId = licenseTypeByPrereqLicenseTypeId;
	}

}
