package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * OrderLabel generated by hbm2java
 */
@Entity
@Table(name = "order_label", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class OrderLabel implements java.io.Serializable {

	private Integer labelId;
	private String name;
	private String description;
	private byte priority;
	private String display;
	private String required;
	private String validationType;
	private String max;
	private String min;
	private boolean dropdownHasNull;
	private String dropdownNullText;
	private Set<OrderCategoryLabelXref> orderCategoryLabelXrefs = new HashSet<OrderCategoryLabelXref>(
			0);
	private Set<Bundle> bundles = new HashSet<Bundle>(0);

	public OrderLabel() {
	}

	public OrderLabel(String name, String description, byte priority,
			String display, String required, String validationType, String max,
			String min, boolean dropdownHasNull, String dropdownNullText) {
		this.name = name;
		this.description = description;
		this.priority = priority;
		this.display = display;
		this.required = required;
		this.validationType = validationType;
		this.max = max;
		this.min = min;
		this.dropdownHasNull = dropdownHasNull;
		this.dropdownNullText = dropdownNullText;
	}

	public OrderLabel(String name, String description, byte priority,
			String display, String required, String validationType, String max,
			String min, boolean dropdownHasNull, String dropdownNullText,
			Set<OrderCategoryLabelXref> orderCategoryLabelXrefs,
			Set<Bundle> bundles) {
		this.name = name;
		this.description = description;
		this.priority = priority;
		this.display = display;
		this.required = required;
		this.validationType = validationType;
		this.max = max;
		this.min = min;
		this.dropdownHasNull = dropdownHasNull;
		this.dropdownNullText = dropdownNullText;
		this.orderCategoryLabelXrefs = orderCategoryLabelXrefs;
		this.bundles = bundles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "label_id", unique = true, nullable = false)
	public Integer getLabelId() {
		return this.labelId;
	}

	public void setLabelId(Integer labelId) {
		this.labelId = labelId;
	}

	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false, length = 16777215)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "priority", nullable = false)
	public byte getPriority() {
		return this.priority;
	}

	public void setPriority(byte priority) {
		this.priority = priority;
	}

	@Column(name = "display", nullable = false, length = 9)
	public String getDisplay() {
		return this.display;
	}

	public void setDisplay(String display) {
		this.display = display;
	}

	@Column(name = "required", nullable = false, length = 4)
	public String getRequired() {
		return this.required;
	}

	public void setRequired(String required) {
		this.required = required;
	}

	@Column(name = "validation_type", nullable = false, length = 17)
	public String getValidationType() {
		return this.validationType;
	}

	public void setValidationType(String validationType) {
		this.validationType = validationType;
	}

	@Column(name = "max", nullable = false)
	public String getMax() {
		return this.max;
	}

	public void setMax(String max) {
		this.max = max;
	}

	@Column(name = "min", nullable = false)
	public String getMin() {
		return this.min;
	}

	public void setMin(String min) {
		this.min = min;
	}

	@Column(name = "dropdown_has_null", nullable = false)
	public boolean isDropdownHasNull() {
		return this.dropdownHasNull;
	}

	public void setDropdownHasNull(boolean dropdownHasNull) {
		this.dropdownHasNull = dropdownHasNull;
	}

	@Column(name = "dropdown_null_text", nullable = false)
	public String getDropdownNullText() {
		return this.dropdownNullText;
	}

	public void setDropdownNullText(String dropdownNullText) {
		this.dropdownNullText = dropdownNullText;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderLabel")
	public Set<OrderCategoryLabelXref> getOrderCategoryLabelXrefs() {
		return this.orderCategoryLabelXrefs;
	}

	public void setOrderCategoryLabelXrefs(
			Set<OrderCategoryLabelXref> orderCategoryLabelXrefs) {
		this.orderCategoryLabelXrefs = orderCategoryLabelXrefs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderLabel")
	public Set<Bundle> getBundles() {
		return this.bundles;
	}

	public void setBundles(Set<Bundle> bundles) {
		this.bundles = bundles;
	}

}
