package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * OrderDiscount generated by hbm2java
 */
@Entity
@Table(name = "order_discount", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = {
		"order_id", "promo_code_id" }))
public class OrderDiscount implements java.io.Serializable {

	private Integer orderDiscountId;
	private PromoCode promoCode;
	private DiscountType discountType;
	private Orders orders;
	private BigDecimal oneTimeDiscount;
	private BigDecimal mrcDiscount;

	public OrderDiscount() {
	}

	public OrderDiscount(DiscountType discountType, Orders orders,
			BigDecimal oneTimeDiscount, BigDecimal mrcDiscount) {
		this.discountType = discountType;
		this.orders = orders;
		this.oneTimeDiscount = oneTimeDiscount;
		this.mrcDiscount = mrcDiscount;
	}

	public OrderDiscount(PromoCode promoCode, DiscountType discountType,
			Orders orders, BigDecimal oneTimeDiscount, BigDecimal mrcDiscount) {
		this.promoCode = promoCode;
		this.discountType = discountType;
		this.orders = orders;
		this.oneTimeDiscount = oneTimeDiscount;
		this.mrcDiscount = mrcDiscount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "order_discount_id", unique = true, nullable = false)
	public Integer getOrderDiscountId() {
		return this.orderDiscountId;
	}

	public void setOrderDiscountId(Integer orderDiscountId) {
		this.orderDiscountId = orderDiscountId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "promo_code_id")
	public PromoCode getPromoCode() {
		return this.promoCode;
	}

	public void setPromoCode(PromoCode promoCode) {
		this.promoCode = promoCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "discount_type_id", nullable = false)
	public DiscountType getDiscountType() {
		return this.discountType;
	}

	public void setDiscountType(DiscountType discountType) {
		this.discountType = discountType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@Column(name = "one_time_discount", nullable = false, precision = 10)
	public BigDecimal getOneTimeDiscount() {
		return this.oneTimeDiscount;
	}

	public void setOneTimeDiscount(BigDecimal oneTimeDiscount) {
		this.oneTimeDiscount = oneTimeDiscount;
	}

	@Column(name = "mrc_discount", nullable = false, precision = 10)
	public BigDecimal getMrcDiscount() {
		return this.mrcDiscount;
	}

	public void setMrcDiscount(BigDecimal mrcDiscount) {
		this.mrcDiscount = mrcDiscount;
	}

}
