package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderTransaction generated by hbm2java
 */
@Entity
@Table(name = "order_transaction", catalog = "fcs")
public class OrderTransaction implements java.io.Serializable {

	private Integer orderTransactionId;
	private PaymentMethod paymentMethod;
	private OrderGroup orderGroup;
	private EntityCreditCard entityCreditCard;
	private BillingSchedule billingSchedule;
	private Integer serverId;
	private Integer customerId;
	private Long netsuiteTransId;
	private BigDecimal amount;
	private String type;
	private String status;
	private Date created;
	private Date updated;
	private Set<OrderTransactionLog> orderTransactionLogs = new HashSet<OrderTransactionLog>(
			0);
	private Set<OrderTransactionItem> orderTransactionItems = new HashSet<OrderTransactionItem>(
			0);

	public OrderTransaction() {
	}

	public OrderTransaction(PaymentMethod paymentMethod, BigDecimal amount,
			String status, Date created, Date updated) {
		this.paymentMethod = paymentMethod;
		this.amount = amount;
		this.status = status;
		this.created = created;
		this.updated = updated;
	}

	public OrderTransaction(PaymentMethod paymentMethod, OrderGroup orderGroup,
			EntityCreditCard entityCreditCard, BillingSchedule billingSchedule,
			Integer serverId, Integer customerId, Long netsuiteTransId,
			BigDecimal amount, String type, String status, Date created,
			Date updated, Set<OrderTransactionLog> orderTransactionLogs,
			Set<OrderTransactionItem> orderTransactionItems) {
		this.paymentMethod = paymentMethod;
		this.orderGroup = orderGroup;
		this.entityCreditCard = entityCreditCard;
		this.billingSchedule = billingSchedule;
		this.serverId = serverId;
		this.customerId = customerId;
		this.netsuiteTransId = netsuiteTransId;
		this.amount = amount;
		this.type = type;
		this.status = status;
		this.created = created;
		this.updated = updated;
		this.orderTransactionLogs = orderTransactionLogs;
		this.orderTransactionItems = orderTransactionItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "order_transaction_id", unique = true, nullable = false)
	public Integer getOrderTransactionId() {
		return this.orderTransactionId;
	}

	public void setOrderTransactionId(Integer orderTransactionId) {
		this.orderTransactionId = orderTransactionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payment_method_id", nullable = false)
	public PaymentMethod getPaymentMethod() {
		return this.paymentMethod;
	}

	public void setPaymentMethod(PaymentMethod paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "order_group_id")
	public OrderGroup getOrderGroup() {
		return this.orderGroup;
	}

	public void setOrderGroup(OrderGroup orderGroup) {
		this.orderGroup = orderGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "credit_card_id")
	public EntityCreditCard getEntityCreditCard() {
		return this.entityCreditCard;
	}

	public void setEntityCreditCard(EntityCreditCard entityCreditCard) {
		this.entityCreditCard = entityCreditCard;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "billing_schedule_id")
	public BillingSchedule getBillingSchedule() {
		return this.billingSchedule;
	}

	public void setBillingSchedule(BillingSchedule billingSchedule) {
		this.billingSchedule = billingSchedule;
	}

	@Column(name = "server_id")
	public Integer getServerId() {
		return this.serverId;
	}

	public void setServerId(Integer serverId) {
		this.serverId = serverId;
	}

	@Column(name = "customer_id")
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "netsuite_trans_id")
	public Long getNetsuiteTransId() {
		return this.netsuiteTransId;
	}

	public void setNetsuiteTransId(Long netsuiteTransId) {
		this.netsuiteTransId = netsuiteTransId;
	}

	@Column(name = "amount", nullable = false, precision = 10)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "type", length = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "status", nullable = false, length = 16)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 0)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderTransaction")
	public Set<OrderTransactionLog> getOrderTransactionLogs() {
		return this.orderTransactionLogs;
	}

	public void setOrderTransactionLogs(
			Set<OrderTransactionLog> orderTransactionLogs) {
		this.orderTransactionLogs = orderTransactionLogs;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "orderTransaction")
	public Set<OrderTransactionItem> getOrderTransactionItems() {
		return this.orderTransactionItems;
	}

	public void setOrderTransactionItems(
			Set<OrderTransactionItem> orderTransactionItems) {
		this.orderTransactionItems = orderTransactionItems;
	}

}
