package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * OrderShipping generated by hbm2java
 */
@Entity
@Table(name = "order_shipping", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = {
		"order_group_id", "shipping_text" }))
public class OrderShipping implements java.io.Serializable {

	private Integer orderShippingId;
	private OrderGroup orderGroup;
	private String shippingText;
	private BigDecimal shippingRate;
	private Set<OrderGroup> orderGroups = new HashSet<OrderGroup>(0);

	public OrderShipping() {
	}

	public OrderShipping(OrderGroup orderGroup, String shippingText,
			BigDecimal shippingRate) {
		this.orderGroup = orderGroup;
		this.shippingText = shippingText;
		this.shippingRate = shippingRate;
	}

	public OrderShipping(OrderGroup orderGroup, String shippingText,
			BigDecimal shippingRate, Set<OrderGroup> orderGroups) {
		this.orderGroup = orderGroup;
		this.shippingText = shippingText;
		this.shippingRate = shippingRate;
		this.orderGroups = orderGroups;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "order_shipping_id", unique = true, nullable = false)
	public Integer getOrderShippingId() {
		return this.orderShippingId;
	}

	public void setOrderShippingId(Integer orderShippingId) {
		this.orderShippingId = orderShippingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_group_id", nullable = false)
	public OrderGroup getOrderGroup() {
		return this.orderGroup;
	}

	public void setOrderGroup(OrderGroup orderGroup) {
		this.orderGroup = orderGroup;
	}

	@Column(name = "shipping_text", nullable = false, length = 64)
	public String getShippingText() {
		return this.shippingText;
	}

	public void setShippingText(String shippingText) {
		this.shippingText = shippingText;
	}

	@Column(name = "shipping_rate", nullable = false, precision = 10)
	public BigDecimal getShippingRate() {
		return this.shippingRate;
	}

	public void setShippingRate(BigDecimal shippingRate) {
		this.shippingRate = shippingRate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderShipping")
	public Set<OrderGroup> getOrderGroups() {
		return this.orderGroups;
	}

	public void setOrderGroups(Set<OrderGroup> orderGroups) {
		this.orderGroups = orderGroups;
	}

}
