package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderBundle generated by hbm2java
 */
@Entity
@Table(name = "order_bundle", catalog = "fcs")
public class OrderBundle implements java.io.Serializable {

	private Integer orderBundleId;
	private OrderGroup orderGroup;
	private Bundle bundle;
	private int quantity;
	private BigDecimal listPrice;
	private BigDecimal discountedPrice;
	private BigDecimal oneTimeTotal;
	private BigDecimal mrcTotal;
	private boolean isRented;
	private Date provisionedOn;
	private Set<OrderBundleDetail> orderBundleDetails = new HashSet<OrderBundleDetail>(
			0);

	public OrderBundle() {
	}

	public OrderBundle(OrderGroup orderGroup, Bundle bundle, int quantity,
			BigDecimal listPrice, BigDecimal discountedPrice,
			BigDecimal mrcTotal, boolean isRented, Date provisionedOn) {
		this.orderGroup = orderGroup;
		this.bundle = bundle;
		this.quantity = quantity;
		this.listPrice = listPrice;
		this.discountedPrice = discountedPrice;
		this.mrcTotal = mrcTotal;
		this.isRented = isRented;
		this.provisionedOn = provisionedOn;
	}

	public OrderBundle(OrderGroup orderGroup, Bundle bundle, int quantity,
			BigDecimal listPrice, BigDecimal discountedPrice,
			BigDecimal oneTimeTotal, BigDecimal mrcTotal, boolean isRented,
			Date provisionedOn, Set<OrderBundleDetail> orderBundleDetails) {
		this.orderGroup = orderGroup;
		this.bundle = bundle;
		this.quantity = quantity;
		this.listPrice = listPrice;
		this.discountedPrice = discountedPrice;
		this.oneTimeTotal = oneTimeTotal;
		this.mrcTotal = mrcTotal;
		this.isRented = isRented;
		this.provisionedOn = provisionedOn;
		this.orderBundleDetails = orderBundleDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "order_bundle_id", unique = true, nullable = false)
	public Integer getOrderBundleId() {
		return this.orderBundleId;
	}

	public void setOrderBundleId(Integer orderBundleId) {
		this.orderBundleId = orderBundleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_group_id", nullable = false)
	public OrderGroup getOrderGroup() {
		return this.orderGroup;
	}

	public void setOrderGroup(OrderGroup orderGroup) {
		this.orderGroup = orderGroup;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "bundle_id", nullable = false)
	public Bundle getBundle() {
		return this.bundle;
	}

	public void setBundle(Bundle bundle) {
		this.bundle = bundle;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "list_price", nullable = false, precision = 10)
	public BigDecimal getListPrice() {
		return this.listPrice;
	}

	public void setListPrice(BigDecimal listPrice) {
		this.listPrice = listPrice;
	}

	@Column(name = "discounted_price", nullable = false, precision = 10)
	public BigDecimal getDiscountedPrice() {
		return this.discountedPrice;
	}

	public void setDiscountedPrice(BigDecimal discountedPrice) {
		this.discountedPrice = discountedPrice;
	}

	@Column(name = "one_time_total", precision = 10)
	public BigDecimal getOneTimeTotal() {
		return this.oneTimeTotal;
	}

	public void setOneTimeTotal(BigDecimal oneTimeTotal) {
		this.oneTimeTotal = oneTimeTotal;
	}

	@Column(name = "mrc_total", nullable = false, precision = 10)
	public BigDecimal getMrcTotal() {
		return this.mrcTotal;
	}

	public void setMrcTotal(BigDecimal mrcTotal) {
		this.mrcTotal = mrcTotal;
	}

	@Column(name = "is_rented", nullable = false)
	public boolean isIsRented() {
		return this.isRented;
	}

	public void setIsRented(boolean isRented) {
		this.isRented = isRented;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "provisioned_on", nullable = false, length = 0)
	public Date getProvisionedOn() {
		return this.provisionedOn;
	}

	public void setProvisionedOn(Date provisionedOn) {
		this.provisionedOn = provisionedOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderBundle")
	public Set<OrderBundleDetail> getOrderBundleDetails() {
		return this.orderBundleDetails;
	}

	public void setOrderBundleDetails(Set<OrderBundleDetail> orderBundleDetails) {
		this.orderBundleDetails = orderBundleDetails;
	}

}
