package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderTransactionLog generated by hbm2java
 */
@Entity
@Table(name = "order_transaction_log", catalog = "fcs")
public class OrderTransactionLog implements java.io.Serializable {

	private Integer orderTransactionLogId;
	private OrderTransaction orderTransaction;
	private BillingSchedule billingSchedule;
	private String level;
	private String module;
	private String function;
	private String message;
	private Date updated;

	public OrderTransactionLog() {
	}

	public OrderTransactionLog(String level, String module, String function,
			String message, Date updated) {
		this.level = level;
		this.module = module;
		this.function = function;
		this.message = message;
		this.updated = updated;
	}

	public OrderTransactionLog(OrderTransaction orderTransaction,
			BillingSchedule billingSchedule, String level, String module,
			String function, String message, Date updated) {
		this.orderTransaction = orderTransaction;
		this.billingSchedule = billingSchedule;
		this.level = level;
		this.module = module;
		this.function = function;
		this.message = message;
		this.updated = updated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "order_transaction_log_id", unique = true, nullable = false)
	public Integer getOrderTransactionLogId() {
		return this.orderTransactionLogId;
	}

	public void setOrderTransactionLogId(Integer orderTransactionLogId) {
		this.orderTransactionLogId = orderTransactionLogId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_transaction_id")
	public OrderTransaction getOrderTransaction() {
		return this.orderTransaction;
	}

	public void setOrderTransaction(OrderTransaction orderTransaction) {
		this.orderTransaction = orderTransaction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "billing_schedule_id")
	public BillingSchedule getBillingSchedule() {
		return this.billingSchedule;
	}

	public void setBillingSchedule(BillingSchedule billingSchedule) {
		this.billingSchedule = billingSchedule;
	}

	@Column(name = "level", nullable = false, length = 5)
	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	@Column(name = "module", nullable = false, length = 128)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "function", nullable = false, length = 128)
	public String getFunction() {
		return this.function;
	}

	public void setFunction(String function) {
		this.function = function;
	}

	@Column(name = "message", nullable = false, length = 16777215)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 0)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

}
