package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * OrderCategoryLabelXref generated by hbm2java
 */
@Entity
@Table(name = "order_category_label_xref", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = {
		"category_id", "label_id" }))
public class OrderCategoryLabelXref implements java.io.Serializable {

	private Integer id;
	private OrderLabel orderLabel;
	private OrderCategory orderCategory;

	public OrderCategoryLabelXref() {
	}

	public OrderCategoryLabelXref(OrderLabel orderLabel,
			OrderCategory orderCategory) {
		this.orderLabel = orderLabel;
		this.orderCategory = orderCategory;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "label_id", nullable = false)
	public OrderLabel getOrderLabel() {
		return this.orderLabel;
	}

	public void setOrderLabel(OrderLabel orderLabel) {
		this.orderLabel = orderLabel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public OrderCategory getOrderCategory() {
		return this.orderCategory;
	}

	public void setOrderCategory(OrderCategory orderCategory) {
		this.orderCategory = orderCategory;
	}

}
