package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * OrderStatus generated by hbm2java
 */
@Entity
@Table(name = "order_status", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class OrderStatus implements java.io.Serializable {

	private Integer orderStatusId;
	private String name;
	private String description;
	private Set<Orders> ordersesForOrderStatusId = new HashSet<Orders>(0);
	private Set<Orders> ordersesForCreditApprovalStatusId = new HashSet<Orders>(
			0);
	private Set<Orders> ordersesForBillingApprovalStatusId = new HashSet<Orders>(
			0);
	private Set<Orders> ordersesForManagerApprovalStatusId = new HashSet<Orders>(
			0);
	private Set<Orders> ordersesForProvisioningStatusId = new HashSet<Orders>(0);

	public OrderStatus() {
	}

	public OrderStatus(String name, String description) {
		this.name = name;
		this.description = description;
	}

	public OrderStatus(String name, String description,
			Set<Orders> ordersesForOrderStatusId,
			Set<Orders> ordersesForCreditApprovalStatusId,
			Set<Orders> ordersesForBillingApprovalStatusId,
			Set<Orders> ordersesForManagerApprovalStatusId,
			Set<Orders> ordersesForProvisioningStatusId) {
		this.name = name;
		this.description = description;
		this.ordersesForOrderStatusId = ordersesForOrderStatusId;
		this.ordersesForCreditApprovalStatusId = ordersesForCreditApprovalStatusId;
		this.ordersesForBillingApprovalStatusId = ordersesForBillingApprovalStatusId;
		this.ordersesForManagerApprovalStatusId = ordersesForManagerApprovalStatusId;
		this.ordersesForProvisioningStatusId = ordersesForProvisioningStatusId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "order_status_id", unique = true, nullable = false)
	public Integer getOrderStatusId() {
		return this.orderStatusId;
	}

	public void setOrderStatusId(Integer orderStatusId) {
		this.orderStatusId = orderStatusId;
	}

	@Column(name = "name", unique = true, nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false, length = 16777215)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderStatusByOrderStatusId")
	public Set<Orders> getOrdersesForOrderStatusId() {
		return this.ordersesForOrderStatusId;
	}

	public void setOrdersesForOrderStatusId(Set<Orders> ordersesForOrderStatusId) {
		this.ordersesForOrderStatusId = ordersesForOrderStatusId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderStatusByCreditApprovalStatusId")
	public Set<Orders> getOrdersesForCreditApprovalStatusId() {
		return this.ordersesForCreditApprovalStatusId;
	}

	public void setOrdersesForCreditApprovalStatusId(
			Set<Orders> ordersesForCreditApprovalStatusId) {
		this.ordersesForCreditApprovalStatusId = ordersesForCreditApprovalStatusId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderStatusByBillingApprovalStatusId")
	public Set<Orders> getOrdersesForBillingApprovalStatusId() {
		return this.ordersesForBillingApprovalStatusId;
	}

	public void setOrdersesForBillingApprovalStatusId(
			Set<Orders> ordersesForBillingApprovalStatusId) {
		this.ordersesForBillingApprovalStatusId = ordersesForBillingApprovalStatusId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderStatusByManagerApprovalStatusId")
	public Set<Orders> getOrdersesForManagerApprovalStatusId() {
		return this.ordersesForManagerApprovalStatusId;
	}

	public void setOrdersesForManagerApprovalStatusId(
			Set<Orders> ordersesForManagerApprovalStatusId) {
		this.ordersesForManagerApprovalStatusId = ordersesForManagerApprovalStatusId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderStatusByProvisioningStatusId")
	public Set<Orders> getOrdersesForProvisioningStatusId() {
		return this.ordersesForProvisioningStatusId;
	}

	public void setOrdersesForProvisioningStatusId(
			Set<Orders> ordersesForProvisioningStatusId) {
		this.ordersesForProvisioningStatusId = ordersesForProvisioningStatusId;
	}

}
