package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Perm generated by hbm2java
 */
@Entity
@Table(name = "perm", catalog = "fcs", uniqueConstraints = {
		@UniqueConstraint(columnNames = "code"),
		@UniqueConstraint(columnNames = "name") })
public class Perm implements java.io.Serializable {

	private Integer permId;
	private Feature feature;
	private String name;
	private String code;
	private String cpVersion;
	private Date created;
	private Date updated;
	private Set<RolePerm> rolePerms = new HashSet<RolePerm>(0);
	private Set<LicensePerm> licensePerms = new HashSet<LicensePerm>(0);

	public Perm() {
	}

	public Perm(String name, String code, String cpVersion, Date created,
			Date updated) {
		this.name = name;
		this.code = code;
		this.cpVersion = cpVersion;
		this.created = created;
		this.updated = updated;
	}

	public Perm(Feature feature, String name, String code, String cpVersion,
			Date created, Date updated, Set<RolePerm> rolePerms,
			Set<LicensePerm> licensePerms) {
		this.feature = feature;
		this.name = name;
		this.code = code;
		this.cpVersion = cpVersion;
		this.created = created;
		this.updated = updated;
		this.rolePerms = rolePerms;
		this.licensePerms = licensePerms;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "perm_id", unique = true, nullable = false)
	public Integer getPermId() {
		return this.permId;
	}

	public void setPermId(Integer permId) {
		this.permId = permId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "feature_id")
	public Feature getFeature() {
		return this.feature;
	}

	public void setFeature(Feature feature) {
		this.feature = feature;
	}

	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "code", unique = true, nullable = false, length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "cp_version", nullable = false, length = 20)
	public String getCpVersion() {
		return this.cpVersion;
	}

	public void setCpVersion(String cpVersion) {
		this.cpVersion = cpVersion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 0)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perm")
	public Set<RolePerm> getRolePerms() {
		return this.rolePerms;
	}

	public void setRolePerms(Set<RolePerm> rolePerms) {
		this.rolePerms = rolePerms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perm")
	public Set<LicensePerm> getLicensePerms() {
		return this.licensePerms;
	}

	public void setLicensePerms(Set<LicensePerm> licensePerms) {
		this.licensePerms = licensePerms;
	}

}
