package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PromoKit generated by hbm2java
 */
@Entity
@Table(name = "promo_kit", catalog = "fcs")
public class PromoKit implements java.io.Serializable {

	private Integer promoKitId;
	private PromoCode promoCode;
	private Bundle bundle;
	private int quantity;
	private Integer bundleLimit;

	public PromoKit() {
	}

	public PromoKit(PromoCode promoCode, Bundle bundle, int quantity) {
		this.promoCode = promoCode;
		this.bundle = bundle;
		this.quantity = quantity;
	}

	public PromoKit(PromoCode promoCode, Bundle bundle, int quantity,
			Integer bundleLimit) {
		this.promoCode = promoCode;
		this.bundle = bundle;
		this.quantity = quantity;
		this.bundleLimit = bundleLimit;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "promo_kit_id", unique = true, nullable = false)
	public Integer getPromoKitId() {
		return this.promoKitId;
	}

	public void setPromoKitId(Integer promoKitId) {
		this.promoKitId = promoKitId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "promo_code_id", nullable = false)
	public PromoCode getPromoCode() {
		return this.promoCode;
	}

	public void setPromoCode(PromoCode promoCode) {
		this.promoCode = promoCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bundle_id", nullable = false)
	public Bundle getBundle() {
		return this.bundle;
	}

	public void setBundle(Bundle bundle) {
		this.bundle = bundle;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "bundle_limit")
	public Integer getBundleLimit() {
		return this.bundleLimit;
	}

	public void setBundleLimit(Integer bundleLimit) {
		this.bundleLimit = bundleLimit;
	}

}
