package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PromoAction generated by hbm2java
 */
@Entity
@Table(name = "promo_action", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = {
		"promo_code_id", "action", "bundle_id" }))
public class PromoAction implements java.io.Serializable {

	private Integer promoActionId;
	private PromoCode promoCode;
	private Bundle bundleByUpgradeBundleId;
	private Bundle bundleByBundleId;
	private String action;
	private String discountType;
	private BigDecimal discountAmount;
	private BigDecimal discountPercent;
	private Integer discountMonths;
	private int minQuantity;
	private Integer maxQuantity;

	public PromoAction() {
	}

	public PromoAction(PromoCode promoCode, Bundle bundleByBundleId,
			String action, String discountType, BigDecimal discountAmount,
			BigDecimal discountPercent, int minQuantity) {
		this.promoCode = promoCode;
		this.bundleByBundleId = bundleByBundleId;
		this.action = action;
		this.discountType = discountType;
		this.discountAmount = discountAmount;
		this.discountPercent = discountPercent;
		this.minQuantity = minQuantity;
	}

	public PromoAction(PromoCode promoCode, Bundle bundleByUpgradeBundleId,
			Bundle bundleByBundleId, String action, String discountType,
			BigDecimal discountAmount, BigDecimal discountPercent,
			Integer discountMonths, int minQuantity, Integer maxQuantity) {
		this.promoCode = promoCode;
		this.bundleByUpgradeBundleId = bundleByUpgradeBundleId;
		this.bundleByBundleId = bundleByBundleId;
		this.action = action;
		this.discountType = discountType;
		this.discountAmount = discountAmount;
		this.discountPercent = discountPercent;
		this.discountMonths = discountMonths;
		this.minQuantity = minQuantity;
		this.maxQuantity = maxQuantity;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "promo_action_id", unique = true, nullable = false)
	public Integer getPromoActionId() {
		return this.promoActionId;
	}

	public void setPromoActionId(Integer promoActionId) {
		this.promoActionId = promoActionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "promo_code_id", nullable = false)
	public PromoCode getPromoCode() {
		return this.promoCode;
	}

	public void setPromoCode(PromoCode promoCode) {
		this.promoCode = promoCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "upgrade_bundle_id")
	public Bundle getBundleByUpgradeBundleId() {
		return this.bundleByUpgradeBundleId;
	}

	public void setBundleByUpgradeBundleId(Bundle bundleByUpgradeBundleId) {
		this.bundleByUpgradeBundleId = bundleByUpgradeBundleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bundle_id", nullable = false)
	public Bundle getBundleByBundleId() {
		return this.bundleByBundleId;
	}

	public void setBundleByBundleId(Bundle bundleByBundleId) {
		this.bundleByBundleId = bundleByBundleId;
	}

	@Column(name = "action", nullable = false, length = 17)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "discount_type", nullable = false, length = 9)
	public String getDiscountType() {
		return this.discountType;
	}

	public void setDiscountType(String discountType) {
		this.discountType = discountType;
	}

	@Column(name = "discount_amount", nullable = false, precision = 10)
	public BigDecimal getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(BigDecimal discountAmount) {
		this.discountAmount = discountAmount;
	}

	@Column(name = "discount_percent", nullable = false, precision = 5)
	public BigDecimal getDiscountPercent() {
		return this.discountPercent;
	}

	public void setDiscountPercent(BigDecimal discountPercent) {
		this.discountPercent = discountPercent;
	}

	@Column(name = "discount_months")
	public Integer getDiscountMonths() {
		return this.discountMonths;
	}

	public void setDiscountMonths(Integer discountMonths) {
		this.discountMonths = discountMonths;
	}

	@Column(name = "min_quantity", nullable = false)
	public int getMinQuantity() {
		return this.minQuantity;
	}

	public void setMinQuantity(int minQuantity) {
		this.minQuantity = minQuantity;
	}

	@Column(name = "max_quantity")
	public Integer getMaxQuantity() {
		return this.maxQuantity;
	}

	public void setMaxQuantity(Integer maxQuantity) {
		this.maxQuantity = maxQuantity;
	}

}
