package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PromoRole generated by hbm2java
 */
@Entity
@Table(name = "promo_role", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = {
		"promo_code_id", "intranet_role_id" }))
public class PromoRole implements java.io.Serializable {

	private Integer promoRoleId;
	private PromoCode promoCode;
	private IntranetRole intranetRole;

	public PromoRole() {
	}

	public PromoRole(PromoCode promoCode, IntranetRole intranetRole) {
		this.promoCode = promoCode;
		this.intranetRole = intranetRole;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "promo_role_id", unique = true, nullable = false)
	public Integer getPromoRoleId() {
		return this.promoRoleId;
	}

	public void setPromoRoleId(Integer promoRoleId) {
		this.promoRoleId = promoRoleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "promo_code_id", nullable = false)
	public PromoCode getPromoCode() {
		return this.promoCode;
	}

	public void setPromoCode(PromoCode promoCode) {
		this.promoCode = promoCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intranet_role_id", nullable = false)
	public IntranetRole getIntranetRole() {
		return this.intranetRole;
	}

	public void setIntranetRole(IntranetRole intranetRole) {
		this.intranetRole = intranetRole;
	}

}
