package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PromoDeployment generated by hbm2java
 */
@Entity
@Table(name = "promo_deployment", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = {
		"promo_code_id", "deployment_id" }))
public class PromoDeployment implements java.io.Serializable {

	private Integer promoDeploymentId;
	private PromoCode promoCode;
	private Deployment deployment;

	public PromoDeployment() {
	}

	public PromoDeployment(PromoCode promoCode, Deployment deployment) {
		this.promoCode = promoCode;
		this.deployment = deployment;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "promo_deployment_id", unique = true, nullable = false)
	public Integer getPromoDeploymentId() {
		return this.promoDeploymentId;
	}

	public void setPromoDeploymentId(Integer promoDeploymentId) {
		this.promoDeploymentId = promoDeploymentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "promo_code_id", nullable = false)
	public PromoCode getPromoCode() {
		return this.promoCode;
	}

	public void setPromoCode(PromoCode promoCode) {
		this.promoCode = promoCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "deployment_id", nullable = false)
	public Deployment getDeployment() {
		return this.deployment;
	}

	public void setDeployment(Deployment deployment) {
		this.deployment = deployment;
	}

}
