package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Provider generated by hbm2java
 */
@Entity
@Table(name = "provider", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Provider implements java.io.Serializable {

	private Integer providerId;
	private Integer providerResellerId;
	private String name;
	private Set<ServerProvider> serverProviders = new HashSet<ServerProvider>(0);
	private Set<ProviderCountry> providerCountries = new HashSet<ProviderCountry>(
			0);

	public Provider() {
	}

	public Provider(String name) {
		this.name = name;
	}

	public Provider(Integer providerResellerId, String name,
			Set<ServerProvider> serverProviders,
			Set<ProviderCountry> providerCountries) {
		this.providerResellerId = providerResellerId;
		this.name = name;
		this.serverProviders = serverProviders;
		this.providerCountries = providerCountries;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "provider_id", unique = true, nullable = false)
	public Integer getProviderId() {
		return this.providerId;
	}

	public void setProviderId(Integer providerId) {
		this.providerId = providerId;
	}

	@Column(name = "provider_reseller_id")
	public Integer getProviderResellerId() {
		return this.providerResellerId;
	}

	public void setProviderResellerId(Integer providerResellerId) {
		this.providerResellerId = providerResellerId;
	}

	@Column(name = "name", unique = true, nullable = false, length = 80)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "provider")
	public Set<ServerProvider> getServerProviders() {
		return this.serverProviders;
	}

	public void setServerProviders(Set<ServerProvider> serverProviders) {
		this.serverProviders = serverProviders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "provider")
	public Set<ProviderCountry> getProviderCountries() {
		return this.providerCountries;
	}

	public void setProviderCountries(Set<ProviderCountry> providerCountries) {
		this.providerCountries = providerCountries;
	}

}
