package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ProviderCountry generated by hbm2java
 */
@Entity
@Table(name = "provider_country", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = {
		"provider_id", "country_id" }))
public class ProviderCountry implements java.io.Serializable {

	private Integer providerCountryId;
	private Provider provider;
	private Country country;

	public ProviderCountry() {
	}

	public ProviderCountry(Provider provider, Country country) {
		this.provider = provider;
		this.country = country;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "provider_country_id", unique = true, nullable = false)
	public Integer getProviderCountryId() {
		return this.providerCountryId;
	}

	public void setProviderCountryId(Integer providerCountryId) {
		this.providerCountryId = providerCountryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "provider_id", nullable = false)
	public Provider getProvider() {
		return this.provider;
	}

	public void setProvider(Provider provider) {
		this.provider = provider;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "country_id", nullable = false)
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

}
