package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RegionAreaCode generated by hbm2java
 */
@Entity
@Table(name = "region_area_code", catalog = "fcs")
public class RegionAreaCode implements java.io.Serializable {

	private Integer regionAreaCodeId;
	private CountryRegion countryRegion;
	private int areaCode;
	private String regionName;

	public RegionAreaCode() {
	}

	public RegionAreaCode(CountryRegion countryRegion, int areaCode,
			String regionName) {
		this.countryRegion = countryRegion;
		this.areaCode = areaCode;
		this.regionName = regionName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "region_area_code_id", unique = true, nullable = false)
	public Integer getRegionAreaCodeId() {
		return this.regionAreaCodeId;
	}

	public void setRegionAreaCodeId(Integer regionAreaCodeId) {
		this.regionAreaCodeId = regionAreaCodeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "country_region_id", nullable = false)
	public CountryRegion getCountryRegion() {
		return this.countryRegion;
	}

	public void setCountryRegion(CountryRegion countryRegion) {
		this.countryRegion = countryRegion;
	}

	@Column(name = "area_code", nullable = false)
	public int getAreaCode() {
		return this.areaCode;
	}

	public void setAreaCode(int areaCode) {
		this.areaCode = areaCode;
	}

	@Column(name = "region_name", nullable = false, length = 28)
	public String getRegionName() {
		return this.regionName;
	}

	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}

}
