package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ResellerType generated by hbm2java
 */
@Entity
@Table(name = "reseller_type", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class ResellerType implements java.io.Serializable {

	private Integer resellerTypeId;
	private String name;
	private Set<ResellerDiscount> resellerDiscounts = new HashSet<ResellerDiscount>(
			0);

	public ResellerType() {
	}

	public ResellerType(String name) {
		this.name = name;
	}

	public ResellerType(String name, Set<ResellerDiscount> resellerDiscounts) {
		this.name = name;
		this.resellerDiscounts = resellerDiscounts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "reseller_type_id", unique = true, nullable = false)
	public Integer getResellerTypeId() {
		return this.resellerTypeId;
	}

	public void setResellerTypeId(Integer resellerTypeId) {
		this.resellerTypeId = resellerTypeId;
	}

	@Column(name = "name", unique = true, nullable = false, length = 80)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resellerType")
	public Set<ResellerDiscount> getResellerDiscounts() {
		return this.resellerDiscounts;
	}

	public void setResellerDiscounts(Set<ResellerDiscount> resellerDiscounts) {
		this.resellerDiscounts = resellerDiscounts;
	}

}
