package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ResellerDiscount generated by hbm2java
 */
@Entity
@Table(name = "reseller_discount", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = {
		"reseller_type_id", "discount_type_id" }))
public class ResellerDiscount implements java.io.Serializable {

	private Integer resellerDiscountId;
	private ResellerType resellerType;
	private DiscountType discountType;
	private BigDecimal discountPercent;

	public ResellerDiscount() {
	}

	public ResellerDiscount(ResellerType resellerType,
			DiscountType discountType, BigDecimal discountPercent) {
		this.resellerType = resellerType;
		this.discountType = discountType;
		this.discountPercent = discountPercent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "reseller_discount_id", unique = true, nullable = false)
	public Integer getResellerDiscountId() {
		return this.resellerDiscountId;
	}

	public void setResellerDiscountId(Integer resellerDiscountId) {
		this.resellerDiscountId = resellerDiscountId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "reseller_type_id", nullable = false)
	public ResellerType getResellerType() {
		return this.resellerType;
	}

	public void setResellerType(ResellerType resellerType) {
		this.resellerType = resellerType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "discount_type_id", nullable = false)
	public DiscountType getDiscountType() {
		return this.discountType;
	}

	public void setDiscountType(DiscountType discountType) {
		this.discountType = discountType;
	}

	@Column(name = "discount_percent", nullable = false, precision = 5)
	public BigDecimal getDiscountPercent() {
		return this.discountPercent;
	}

	public void setDiscountPercent(BigDecimal discountPercent) {
		this.discountPercent = discountPercent;
	}

}
