package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * RoleTollrestriction generated by hbm2java
 */
@Entity
@Table(name = "role_tollrestriction", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = {
		"role_id", "content" }))
public class RoleTollrestriction implements java.io.Serializable {

	private Integer roleTollrestrictionId;
	private Role role;
	private String type;
	private String content;
	private Date updated;

	public RoleTollrestriction() {
	}

	public RoleTollrestriction(Role role, String type, String content,
			Date updated) {
		this.role = role;
		this.type = type;
		this.content = content;
		this.updated = updated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "role_tollrestriction_id", unique = true, nullable = false)
	public Integer getRoleTollrestrictionId() {
		return this.roleTollrestrictionId;
	}

	public void setRoleTollrestrictionId(Integer roleTollrestrictionId) {
		this.roleTollrestrictionId = roleTollrestrictionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "type", nullable = false, length = 13)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "content", nullable = false, length = 80)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 0)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

}
