package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ServerBundle generated by hbm2java
 */
@Entity
@Table(name = "server_bundle", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = {
		"server_id", "bundle_id" }))
public class ServerBundle implements java.io.Serializable {

	private Integer serverBundleId;
	private Bundle bundle;
	private int serverId;
	private Date created;

	public ServerBundle() {
	}

	public ServerBundle(Bundle bundle, int serverId, Date created) {
		this.bundle = bundle;
		this.serverId = serverId;
		this.created = created;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "server_bundle_id", unique = true, nullable = false)
	public Integer getServerBundleId() {
		return this.serverBundleId;
	}

	public void setServerBundleId(Integer serverBundleId) {
		this.serverBundleId = serverBundleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bundle_id", nullable = false)
	public Bundle getBundle() {
		return this.bundle;
	}

	public void setBundle(Bundle bundle) {
		this.bundle = bundle;
	}

	@Column(name = "server_id", nullable = false)
	public int getServerId() {
		return this.serverId;
	}

	public void setServerId(int serverId) {
		this.serverId = serverId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
