package com.fonality.bu.entity;

// Generated Feb 8, 2013 10:59:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sessions generated by hbm2java
 */
@Entity
@Table(name = "sessions", catalog = "fcs")
public class Sessions implements java.io.Serializable {

	private String id;
	private String ASession;

	public Sessions() {
	}

	public Sessions(String id, String ASession) {
		this.id = id;
		this.ASession = ASession;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "a_session", nullable = false, length = 65535)
	public String getASession() {
		return this.ASession;
	}

	public void setASession(String ASession) {
		this.ASession = ASession;
	}

}
