package com.fonality.bu.entity;

// Generated Feb 8, 2013 10:59:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SmRegistry generated by hbm2java
 */
@Entity
@Table(name = "sm_registry", catalog = "fcs")
public class SmRegistry implements java.io.Serializable {

	private Integer id;
	private String familyname;
	private String smHost;
	private int smPid;
	private String guid;
	private String objectname;
	private String objectMessage;
	private Date createDate;
	private Date updated;
	private int port;

	public SmRegistry() {
	}

	public SmRegistry(String familyname, String smHost, int smPid, String guid,
			String objectname, String objectMessage, Date createDate,
			Date updated, int port) {
		this.familyname = familyname;
		this.smHost = smHost;
		this.smPid = smPid;
		this.guid = guid;
		this.objectname = objectname;
		this.objectMessage = objectMessage;
		this.createDate = createDate;
		this.updated = updated;
		this.port = port;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "familyname", nullable = false, length = 16)
	public String getFamilyname() {
		return this.familyname;
	}

	public void setFamilyname(String familyname) {
		this.familyname = familyname;
	}

	@Column(name = "sm_host", nullable = false, length = 115)
	public String getSmHost() {
		return this.smHost;
	}

	public void setSmHost(String smHost) {
		this.smHost = smHost;
	}

	@Column(name = "sm_pid", nullable = false)
	public int getSmPid() {
		return this.smPid;
	}

	public void setSmPid(int smPid) {
		this.smPid = smPid;
	}

	@Column(name = "guid", nullable = false, length = 36)
	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	@Column(name = "objectname", nullable = false, length = 32)
	public String getObjectname() {
		return this.objectname;
	}

	public void setObjectname(String objectname) {
		this.objectname = objectname;
	}

	@Column(name = "object_message", nullable = false, length = 65535)
	public String getObjectMessage() {
		return this.objectMessage;
	}

	public void setObjectMessage(String objectMessage) {
		this.objectMessage = objectMessage;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 0)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 0)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "port", nullable = false)
	public int getPort() {
		return this.port;
	}

	public void setPort(int port) {
		this.port = port;
	}

}
