package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TaxMapping generated by hbm2java
 */
@Entity
@Table(name = "tax_mapping", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ns_tax_schedule", "bs_trans_type", "bs_service_type" }))
public class TaxMapping implements java.io.Serializable {

	private Integer taxMappingId;
	private String nsTaxSchedule;
	private String nsDescription;
	private int bsTransType;
	private int bsServiceType;
	private String bsDescription;
	private Date created;
	private Date updated;
	private Set<BundlePriceModel> bundlePriceModels = new HashSet<BundlePriceModel>(
			0);

	public TaxMapping() {
	}

	public TaxMapping(String nsTaxSchedule, String nsDescription,
			int bsTransType, int bsServiceType, String bsDescription,
			Date created, Date updated) {
		this.nsTaxSchedule = nsTaxSchedule;
		this.nsDescription = nsDescription;
		this.bsTransType = bsTransType;
		this.bsServiceType = bsServiceType;
		this.bsDescription = bsDescription;
		this.created = created;
		this.updated = updated;
	}

	public TaxMapping(String nsTaxSchedule, String nsDescription,
			int bsTransType, int bsServiceType, String bsDescription,
			Date created, Date updated, Set<BundlePriceModel> bundlePriceModels) {
		this.nsTaxSchedule = nsTaxSchedule;
		this.nsDescription = nsDescription;
		this.bsTransType = bsTransType;
		this.bsServiceType = bsServiceType;
		this.bsDescription = bsDescription;
		this.created = created;
		this.updated = updated;
		this.bundlePriceModels = bundlePriceModels;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tax_mapping_id", unique = true, nullable = false)
	public Integer getTaxMappingId() {
		return this.taxMappingId;
	}

	public void setTaxMappingId(Integer taxMappingId) {
		this.taxMappingId = taxMappingId;
	}

	@Column(name = "ns_tax_schedule", nullable = false, length = 10)
	public String getNsTaxSchedule() {
		return this.nsTaxSchedule;
	}

	public void setNsTaxSchedule(String nsTaxSchedule) {
		this.nsTaxSchedule = nsTaxSchedule;
	}

	@Column(name = "ns_description", nullable = false, length = 16777215)
	public String getNsDescription() {
		return this.nsDescription;
	}

	public void setNsDescription(String nsDescription) {
		this.nsDescription = nsDescription;
	}

	@Column(name = "bs_trans_type", nullable = false)
	public int getBsTransType() {
		return this.bsTransType;
	}

	public void setBsTransType(int bsTransType) {
		this.bsTransType = bsTransType;
	}

	@Column(name = "bs_service_type", nullable = false)
	public int getBsServiceType() {
		return this.bsServiceType;
	}

	public void setBsServiceType(int bsServiceType) {
		this.bsServiceType = bsServiceType;
	}

	@Column(name = "bs_description", nullable = false, length = 16777215)
	public String getBsDescription() {
		return this.bsDescription;
	}

	public void setBsDescription(String bsDescription) {
		this.bsDescription = bsDescription;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 0)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taxMapping")
	public Set<BundlePriceModel> getBundlePriceModels() {
		return this.bundlePriceModels;
	}

	public void setBundlePriceModels(Set<BundlePriceModel> bundlePriceModels) {
		this.bundlePriceModels = bundlePriceModels;
	}

}
