package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TransactionSubmit generated by hbm2java
 */
@Entity
@Table(name = "transaction_submit", catalog = "fcs")
public class TransactionSubmit implements java.io.Serializable {

	private Integer transactionSubmitId;
	private String familyname;
	private byte[] input;
	private String status;
	private Date created;
	private Date updated;
	private Set<TransactionJob> transactionJobs = new HashSet<TransactionJob>(0);
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public TransactionSubmit() {
	}

	public TransactionSubmit(String familyname, byte[] input, String status,
			Date created, Date updated) {
		this.familyname = familyname;
		this.input = input;
		this.status = status;
		this.created = created;
		this.updated = updated;
	}

	public TransactionSubmit(String familyname, byte[] input, String status,
			Date created, Date updated, Set<TransactionJob> transactionJobs,
			Set<Orders> orderses) {
		this.familyname = familyname;
		this.input = input;
		this.status = status;
		this.created = created;
		this.updated = updated;
		this.transactionJobs = transactionJobs;
		this.orderses = orderses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "transaction_submit_id", unique = true, nullable = false)
	public Integer getTransactionSubmitId() {
		return this.transactionSubmitId;
	}

	public void setTransactionSubmitId(Integer transactionSubmitId) {
		this.transactionSubmitId = transactionSubmitId;
	}

	@Column(name = "familyname", nullable = false, length = 16)
	public String getFamilyname() {
		return this.familyname;
	}

	public void setFamilyname(String familyname) {
		this.familyname = familyname;
	}

	@Column(name = "input", nullable = false)
	public byte[] getInput() {
		return this.input;
	}

	public void setInput(byte[] input) {
		this.input = input;
	}

	@Column(name = "status", nullable = false, length = 7)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 0)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transactionSubmit")
	public Set<TransactionJob> getTransactionJobs() {
		return this.transactionJobs;
	}

	public void setTransactionJobs(Set<TransactionJob> transactionJobs) {
		this.transactionJobs = transactionJobs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transactionSubmit")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
