package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TransactionStep generated by hbm2java
 */
@Entity
@Table(name = "transaction_step", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = {
		"familyname", "sequence_name" }))
public class TransactionStep implements java.io.Serializable {

	private Integer transactionStepId;
	private String familyname;
	private String sequenceName;
	private String objectname;
	private String objectargs;
	private String sequenceSuccess;
	private String sequenceFailure;
	private String objectlocation;
	private byte iterations;
	private Set<TransactionJob> transactionJobs = new HashSet<TransactionJob>(0);

	public TransactionStep() {
	}

	public TransactionStep(String familyname, String sequenceName,
			String objectname, String objectargs, String sequenceSuccess,
			String sequenceFailure, String objectlocation, byte iterations) {
		this.familyname = familyname;
		this.sequenceName = sequenceName;
		this.objectname = objectname;
		this.objectargs = objectargs;
		this.sequenceSuccess = sequenceSuccess;
		this.sequenceFailure = sequenceFailure;
		this.objectlocation = objectlocation;
		this.iterations = iterations;
	}

	public TransactionStep(String familyname, String sequenceName,
			String objectname, String objectargs, String sequenceSuccess,
			String sequenceFailure, String objectlocation, byte iterations,
			Set<TransactionJob> transactionJobs) {
		this.familyname = familyname;
		this.sequenceName = sequenceName;
		this.objectname = objectname;
		this.objectargs = objectargs;
		this.sequenceSuccess = sequenceSuccess;
		this.sequenceFailure = sequenceFailure;
		this.objectlocation = objectlocation;
		this.iterations = iterations;
		this.transactionJobs = transactionJobs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "transaction_step_id", unique = true, nullable = false)
	public Integer getTransactionStepId() {
		return this.transactionStepId;
	}

	public void setTransactionStepId(Integer transactionStepId) {
		this.transactionStepId = transactionStepId;
	}

	@Column(name = "familyname", nullable = false, length = 16)
	public String getFamilyname() {
		return this.familyname;
	}

	public void setFamilyname(String familyname) {
		this.familyname = familyname;
	}

	@Column(name = "sequence_name", nullable = false, length = 8)
	public String getSequenceName() {
		return this.sequenceName;
	}

	public void setSequenceName(String sequenceName) {
		this.sequenceName = sequenceName;
	}

	@Column(name = "objectname", nullable = false)
	public String getObjectname() {
		return this.objectname;
	}

	public void setObjectname(String objectname) {
		this.objectname = objectname;
	}

	@Column(name = "objectargs", nullable = false)
	public String getObjectargs() {
		return this.objectargs;
	}

	public void setObjectargs(String objectargs) {
		this.objectargs = objectargs;
	}

	@Column(name = "sequence_success", nullable = false, length = 8)
	public String getSequenceSuccess() {
		return this.sequenceSuccess;
	}

	public void setSequenceSuccess(String sequenceSuccess) {
		this.sequenceSuccess = sequenceSuccess;
	}

	@Column(name = "sequence_failure", nullable = false, length = 8)
	public String getSequenceFailure() {
		return this.sequenceFailure;
	}

	public void setSequenceFailure(String sequenceFailure) {
		this.sequenceFailure = sequenceFailure;
	}

	@Column(name = "objectlocation", nullable = false)
	public String getObjectlocation() {
		return this.objectlocation;
	}

	public void setObjectlocation(String objectlocation) {
		this.objectlocation = objectlocation;
	}

	@Column(name = "iterations", nullable = false)
	public byte getIterations() {
		return this.iterations;
	}

	public void setIterations(byte iterations) {
		this.iterations = iterations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transactionStep")
	public Set<TransactionJob> getTransactionJobs() {
		return this.transactionJobs;
	}

	public void setTransactionJobs(Set<TransactionJob> transactionJobs) {
		this.transactionJobs = transactionJobs;
	}

}
