package com.fonality.bu.entity;

// Generated Mar 21, 2013 12:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * UserLicense generated by hbm2java
 */
@Entity
@Table(name = "user_license", catalog = "fcs", uniqueConstraints = @UniqueConstraint(columnNames = {
		"user_id", "license_type_id" }))
public class UserLicense implements java.io.Serializable {

	private Integer userLicenseId;
	private LicenseType licenseType;
	private int userId;
	private Date created;

	public UserLicense() {
	}

	public UserLicense(LicenseType licenseType, int userId, Date created) {
		this.licenseType = licenseType;
		this.userId = userId;
		this.created = created;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_license_id", unique = true, nullable = false)
	public Integer getUserLicenseId() {
		return this.userLicenseId;
	}

	public void setUserLicenseId(Integer userLicenseId) {
		this.userLicenseId = userLicenseId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "license_type_id", nullable = false)
	public LicenseType getLicenseType() {
		return this.licenseType;
	}

	public void setLicenseType(LicenseType licenseType) {
		this.licenseType = licenseType;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
